
// src/context/language-context.tsx
'use client';

import type { ReactNode } from 'react';
import { createContext, useContext, useEffect, useState, useCallback } from 'react';

export type Language = 'en' | 'it' | 'es' | 'fr';
const DEFAULT_LANGUAGE: Language = 'en';
const LANGUAGE_STORAGE_KEY = 'app-language';

interface Translations {
  [key: string]: string | Translations;
}

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      home: 'Home',
      exercises: 'Exercises',
      workoutPlans: 'Workout Plans',
      calendar: 'Calendar',
      progress: 'Progress',
      diet: 'Diet',
    },
    userDropdown: {
      myAccount: 'My Account',
      settings: 'Settings',
      logout: 'Log out',
    },
    header: {
      toggleTheme: 'Toggle theme',
      openMenu: 'Open menu',
    },
    dashboard: {
      welcomeTitle: 'Welcome to SickFit Pro!',
      welcomeDescription: "Your journey to peak fitness starts here. Let's get to work.",
      workoutsThisWeek: 'Workouts This Week',
      weightLifted: 'Total Weight Lifted',
      currentWeight: 'Current Weight',
      logNewWorkout: 'Start Workout',
      todaysFocus: "Today's Focus",
      todaysFocusDescription: "What's on the agenda for today?",
      checkCalendarForWorkout: "Check your calendar for today's workout!",
      viewCalendarToSeeWorkout: "Your scheduled workout will appear here.",
      viewFullSchedule: 'View Full Schedule',
      activityAndHistoryTitle: "Activity & History",
      noWorkoutHistory: "No workout history yet. Complete a workout to see it here!",
      viewAllHistoryButton: "View All History",
      todayIsRestDay: "Today is a rest day! Enjoy it! 😊",
      noWorkoutScheduledForToday: "No workout scheduled for today.",
    },
    waterIntakeCard: {
      title: "Water Intake",
      currentIntakeLabel: "Current: {current}ml / {dailyGoal}ml",
      setDailyGoalLabel: "Daily Goal (ml)", 
      saveGoalButton: "Save Goal",
      goalSavedTitle: "Goal Saved",
      goalSavedDescription: "Your daily water intake goal has been updated.",
      errorInvalidGoal: "Please enter a valid goal.",
      resetWaterButton: "Reset Water",
      waterResetTitle: "Water Reset",
      waterResetDescription: "Your water intake for the day has been reset.",
      goalSettingsButtonLabel: "Goal Settings", 
      goalSettingsAriaLabel: "Goal Settings",
      goalSettingsTooltip: "Set your daily water goal",
      ariaAddGlass: "Add glass ({amount}ml)",
      ariaAddBottle: "Add bottle ({amount}ml)",
      tooltipAddAmount: "+{amount}ml",
      reminderLabel: "Hydration Reminder",
      selectReminderFrequencyPlaceholder: "Set reminder frequency",
      reminderOff: "Off",
      reminderDaily: "Daily",
      reminderHourly: "Hourly",
      hydrationReminderSettingsAriaLabel: "Hydration Reminder Settings",
      hydrationReminderTooltip: "Set hydration reminder",
    },
    macroTrackingCard: {
        title: "Macro Tracking",
        proteinLabel: "Protein",
        carbsLabel: "Carbs",
        fatLabel: "Fat",
        setYourWeeklyGoals: "Set Your Weekly Macro Goals",
        selectDay: "Select Day",
        saveGoalsButton: "Save Goals for Day",
        goalsSavedTitle: "Macro Goals Saved",
        goalsForDaySaved: "Goals for {dayOfWeek} saved successfully!",
        monthlyTotalsTitle: "Estimated Monthly Totals", 
        totalProteinMonth: "Total Protein (Month)", 
        totalCarbsMonth: "Total Carbs (Month)", 
        totalFatMonth: "Total Fat (Month)", 
        unitGrams: "g",
        loadingTotals: "Calculating monthly totals...", 
        macroTrendChartTitle: "Macronutrient Goal Trends",
        dailyTab: "Daily",
        weeklyTab: "Weekly",
        monthlyTab: "Monthly",
        weekLabel: "Week {weekNum}",
        macroReminderSettingsAriaLabel: "Macro reminder settings",
        macroReminderTooltip: "Set macro logging reminder",
        goalSettingsButtonAriaLabel: "Macro Goal Settings", 
        goalSettingsTooltip: "Set weekly macro goals", 
    },
    aiHealthAdvisor: {
        cardTitle: "AI Health Advisor",
        dataUsageInfo: "Your stored macro goals, water intake goal, body measurements, and training summary will be automatically used by the AI to provide personalized advice. You can also ask a specific question below.",
        userQueryLabel: "Your Specific Question (Optional)",
        userQueryPlaceholder: "e.g., How can I improve my sleep? or What are some good exercises for lower back pain?",
        userQueryDescription: "Ask a specific question or leave blank for general advice based on your data.",
        userQueryMinError: "If asking a question, please provide at least 10 characters.",
        getAdviceButton: "Get AI Health Advice",
        adviceReadyTitle: "Health Advice Ready!",
        adviceReadyDescription: "AI has generated health advice for you.",
        errorTitle: "Advisor Error",
        errorDescription: "Failed to get AI health advice. Please try again.",
        resultsTitle: "AI Health Advisor Results",
        overallAssessment: "Overall Assessment",
        specificAdvice: "Specific Advice",
    },
    settingsPage: {
      title: 'Settings',
      language: 'Language',
      selectLanguage: 'Select language',
      english: 'English (US)',
      italian: 'Italiano (Italian)',
      spanish: 'Español (Spanish)',
      french: 'Français (French)',
      notifications: 'Notifications',
      allNotificationsLabel: 'Enable All App Notifications',
      saveChanges: 'Save Changes',
      settingsSaved: 'Settings Saved',
      preferencesUpdated: 'Your preferences have been updated',
      profileInformationTitle: 'Profile Information',
      uploadProfilePictureLabel: 'Profile Picture',
      profilePictureAlt: 'Profile Picture',
      photoSizeError: 'Photo size should not exceed 2MB.',
      photoSizeLimit: 'Max 2MB. Recommended square aspect ratio.',
      nameLabel: 'Name',
      namePlaceholder: 'Enter your name',
      emailLabel: 'Email',
      emailCannotBeChanged: 'Email cannot be changed here.',
      accountSecurityTitle: 'Account Security',
      currentPasswordLabel: 'Current Password',
      newPasswordLabel: 'New Password',
      newPasswordPlaceholder: 'Enter new password (min. 8 characters)',
      confirmNewPasswordLabel: 'Confirm New Password',
      confirmNewPasswordPlaceholder: 'Confirm new password',
      passwordMismatchError: 'New passwords do not match.',
      passwordChangedTitle: 'Password Changed',
      passwordChangedSuccess: 'Your password has been updated successfully.',
      currentPasswordRequiredError: 'Current password is required to set a new one.',
      noChangesMadeTitle: 'No Changes',
      noChangesMadeDescription: 'No settings were modified.',
      toastErrorTitle: 'Error',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      currentWeightLabel: 'Current Weight (kg)',
      currentWeightPlaceholder: 'e.g., 70.5',
    },
    aiSplitForm: {
        cardTitle: "AI Fitness Advisor",
        generateAdviceButton: "Generate Advice",
        generatingSplitTitle: "Generating your advice...",
        generatingSplitDescription: "Our AI is thinking. This might take a moment.",
        yourSuggestedAdviceTitle: "Your AI Fitness Advice",
        suggestedKeyPointsLabel: "Key Suggestions:",
        detailedAnalysisLabel: "Detailed Analysis & Advice:",
        toastSuggestionReadyTitle: "Advice Ready!",
        toastSuggestionReadyDescription: "AI has generated training advice for you.",
        toastErrorTitle: "Error",
        toastErrorDescription: "Failed to get AI advice. Please try again.",
        errorFetchingHistory: "Could not automatically retrieve your training history. Please ensure you have some logged workouts.",
        noHistoryForAdvice: "No training history available to generate advice.",
        genericGoalForAdvice: "General improvement based on training history and progress data.",
        promptGenerateAdvice: "Click the button above to generate personalized training advice based on your progress data."
    },
    calendarPage: {
        title: "Workout Calendar",
        description: "Plan and track your weekly training schedule.",
        selectADate: "Select a Date",
        workoutsScheduledForThisDay: "Workouts scheduled for this day.",
        addWorkoutToDay: "Add Workout",
        noWorkoutsScheduled: "No workouts scheduled for this day.",
        selectDateToSeeWorkouts: "Select a date to see scheduled workouts.",
        dialogAddWorkoutTitle: "Add Workout to {dayOfWeek}",
        dialogAddWorkoutDescription: "Select a workout plan to schedule for this day of the week.",
        workoutPlanLabel: "Workout Plan",
        selectAPlanPlaceholder: "Select a plan",
        samplePlan1: "Full Body Blast",
        samplePlan2: "Upper Body Power",
        samplePlan3: "Leg Day Domination",
        samplePlan4: "Cardio Session",
        cancelButton: "Cancel",
        scheduleWorkoutButton: "Schedule Workout",
        loadingCalendar: "Loading calendar...",
        weeklyScheduleTitle: "Weekly Training Schedule",
        weeklyScheduleDescription: "Set up your typical training week. This schedule will repeat automatically.",
        days: {
          monday: "Monday",
          tuesday: "Tuesday",
          wednesday: "Wednesday",
          thursday: "Thursday",
          friday: "Friday",
          saturday: "Saturday",
          sunday: "Sunday",
        },
        noWorkoutsForDayOfWeek: "No workouts scheduled for {dayOfWeek}.",
        addWorkoutTo: "Add to {dayOfWeek}",
        toastWorkoutScheduledTitle: "Workout Scheduled!",
        toastWorkoutScheduledDescriptionNoTime: "{planName} on {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Workout Removed",
        errorSelectDayAndPlan: "Please select a day and a workout plan.",
        errorPlanNotFound: "Selected plan not found.",
    },
    exercisesPage: {
        title: "Custom Exercises",
        description: "Manage your personalized exercise library.",
        addNewExerciseButton: "Add New Exercise",
        yourExercisesCardTitle: "Your Exercises",
        tableHeaderName: "Name",
        tableHeaderMuscleGroup: "Muscle Group",
        tableHeaderType: "Type",
        tableHeaderActions: "Actions",
        dialogAddTitle: "Add New Exercise",
        dialogAddDescription: "Fill in the details for your new exercise.",
        dialogEditTitle: "Edit Exercise",
        dialogEditDescription: "Update the details of your exercise.",
        formNameLabel: "Name",
        formDescriptionLabel: "Description",
        formMuscleGroupLabel: "Muscle Group",
        selectMuscleGroupPlaceholder: "Select muscle group",
        muscleGroupChest: "Chest",
        muscleGroupBack: "Back",
        muscleGroupLegs: "Legs",
        muscleGroupShoulders: "Shoulders",
        muscleGroupBiceps: "Biceps",
        muscleGroupTriceps: "Triceps",
        muscleGroupAbs: "Abs",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Other",
        formTypeLabel: "Type",
        selectExerciseTypePlaceholder: "Select exercise type",
        typeStrength: "Strength",
        typeCardio: "Cardio",
        typeFlexibility: "Flexibility",
        typePlyometrics: "Plyometrics",
        typeOther: "Other",
        cancelButton: "Cancel",
        saveExerciseButton: "Save Exercise",
    },
    progressPage: {
        title: "Progress Tracking",
        description: "Visualize your fitness journey and celebrate your achievements.",
        performanceMetricsCardTitle: "Performance Metrics",
        bodyCompositionCardTitle: "Body Composition",
        weightLabel: "Weight (kg)",
        photoComparisonCardTitle: "Photo Comparison",
        beforePhotoLabel: "Before Photo",
        afterPhotoLabel: "After Photo",
        noPhotoUploaded: "No photo uploaded",
        clickToUpload: "Click to upload",
        uploadButtonLabel: "Upload",
        bodyMeasurementsCardTitle: "Body Measurements",
        addMeasurementButton: "Add Measurement",
        measurementDialogAddTitle: "Add New Measurement",
        measurementDialogEditTitle: "Edit Measurement",
        measurementDialogDescription: "Enter the details for your measurement.",
        formDateLabel: "Date",
        formMeasurementNameLabel: "Measurement Type",
        selectMeasurementNamePlaceholder: "Select measurement type",
        measurementNameBiceps: "Biceps",
        measurementNameChest: "Chest",
        measurementNameWaist: "Waist",
        measurementNameHips: "Hips",
        measurementNameThigh: "Thigh",
        measurementNameCalf: "Calf",
        measurementNameWeight: "Weight",
        measurementNameHeight: "Height",
        formValueLabel: "Value",
        formUnitLabel: "Unit",
        unitCM: "cm",
        unitIN: "in",
        unitKG: "kg",
        unitLBS: "lbs",
        formNotesLabel: "Notes",
        formNotesPlaceholder: "Enter any relevant notes...",
        saveMeasurementButton: "Save Measurement",
        tableHeaderDate: "Date",
        tableHeaderMeasurementName: "Measurement",
        tableHeaderValue: "Value",
        measurementReminderLabel: "Measurement Reminder",
        selectReminderFrequencyPlaceholder: "Set reminder frequency",
        reminderOff: "Off",
        reminderDaily: "Daily",
        reminderWeekly: "Weekly",
        reminderBiWeekly: "Bi-Weekly",
        reminderMonthly: "Monthly",
        measurementSaved: "Measurement Saved",
        measurementDeleted: "Measurement Deleted",
        noMeasurementsYet: "No measurements recorded yet. Add your first one!",
        formValidationAlert: "Please fill in date, measurement type, and value.",
        timeRangeWeekly: "Weekly",
        timeRangeMonthly: "Monthly",
        timeRangeYearly: "Yearly",
        muscleGroupChestChart: "Chest (Volume)",
        muscleGroupBackChart: "Back (Volume)",
        muscleGroupLegsChart: "Legs (Volume)",
        muscleGroupShouldersChart: "Shoulders (Volume)",
        muscleGroupBicepsChart: "Biceps (Volume)",
        muscleGroupTricepsChart: "Triceps (Volume)",
        weekShortLabel: "W{num}",
        weeklyTrainingVolumeLabel: "Training Volume", // For Y-axis label
    },
    workoutPlansPage: {
        title: "Workout Plans",
        description: "Create, manage, and share your training schedules.",
        createNewPlanButton: "Create New Plan",
        estDurationLabel: "Est. Duration", 
        exercisesLabel: "Exercises",
        involvedMusclesLabel: "Muscles Involved:",
        startButton: "Start",
        dialogEditTitle: "Edit Workout Plan",
        dialogEditDescription: "Update the details of your workout plan.",
        dialogCreateTitle: "Create New Workout Plan",
        dialogCreateDescription: "Design your new workout plan.",
        planNameLabel: "Plan Name",
        descriptionLabel: "Description",
        exerciseNameLabel: "Exercise Name",
        setsLabel: "Sets",
        repsLabel: "Reps",
        addThisExerciseButton: "Add this Exercise",
        addedExercisesLabel: "Added Exercises:",
        noExercisesAddedYet: "No exercises added to this plan yet.",
        exerciseSelectionPlaceholder: "Add exercises to this plan using the form above.",
        addExerciseButton: "Add Exercise to Plan",
        cancelButton: "Cancel",
        savePlanButton: "Save Plan",
        toastPlanUpdatedTitle: "Plan Updated",
        toastPlanUpdatedDescription: "\"{planName}\" has been updated.",
        toastPlanCreatedTitle: "Plan Created",
        toastPlanCreatedDescription: "\"{planName}\" has been created.",
        toastPlanDeletedTitle: "Plan Deleted",
        toastPlanDeletedDescription: "\"{planName}\" has been deleted.",
        toastLinkCopiedTitle: "Link Copied!",
        toastLinkCopiedDescription: "Workout plan link copied to clipboard.",
        muscleSilhouetteAlt: "Muscle groups involved in the plan",
        noMuscleGroupsSpecified: "N/A"
    },
     startWorkoutPage: {
      title: "Start New Workout",
      description: "Choose a plan to start or begin an ad-hoc session.",
      selectPlanTitle: "Select a Plan",
      startAdHocButton: "Start Ad-hoc Workout",
      noPlansAvailable: "No workout plans available. Create one first!",
      startPlanButton: "Start Plan",
    },
    activeWorkoutPage: {
      title: "Active Workout: {planName}",
      description: "Track your sets, reps, and weights for this session.",
      finishWorkoutButton: "Finish Workout",
      logSetButton: "Log Set",
      planNotFound: "Workout plan not found.",
      planNotFoundDescription: "Please check the URL or go back to select a valid plan.",
      loadingWorkout: "Loading Workout...",
      loadingDescription: "Please wait while we fetch the plan details.",
      targetSetsLabel: "Target Sets",
      targetRepsLabel: "Target Reps",
      repsInputLabel: "Reps",
      weightInputLabel: "Weight (kg)",
      setColumnLabel: "Set",
      dateColumnLabel: "Date",
      repsColumnLabel: "Reps",
      weightColumnLabel: "Weight (kg)",
      toastSetLoggedTitle: "Set Logged",
      toastSetLoggedDescription: "Set for {exerciseName} recorded.",
      toastSetDeletedTitle: "Set Deleted",
      toastWorkoutFinishedTitle: "Workout Finished!",
      toastWorkoutFinishedDescription: "Great job completing your workout in {duration}!",
      overallProgressLabel: "Overall Workout Progress",
      setCompletionLabel: "Sets: {completed}/{total}",
      noGifAvailable: "No GIF available",
      exerciseDemoAlt: "exercise demonstration",
      nextExerciseButton: "Next Exercise",
      completeWorkoutButton: "Complete Workout",
      workoutCompleteTitle: "Workout Complete!",
      workoutCompleteDescription: "You've successfully completed the {planName} workout.",
      totalTimeLabel: "Total Time",
      backToDashboardButton: "Back to Home",
      confirmFinishTitle: "Finish Workout?",
      confirmFinishDescription: "Are you sure you want to mark this workout as complete?",
      confirmFinishButton: "Yes, Finish",
      noSetsLoggedYet: "No sets logged for this exercise yet.",
      sessionPBsLabel: "Session PBs",
      maxWeightLabel: "Max Weight",
      maxRepsLabel: "Max Reps",
      repsUnitLabel: "reps",
      workoutInProgressTitle: "Workout In Progress",
      finishCurrentWorkoutPrompt: "You have an active workout. Please finish or abandon it before starting a new one or creating/editing plans.",
    },
    dietPage: {
        title: "Diet Tracking",
        description: "Manage your daily nutritional intake and hydration.",
    },
    toastErrorTitle: "Error",
    resumeWorkoutButton: {
      resumeTitle: "Resume Workout",
      resume: "Resume: {planName}",
    },
    supplements: {
        cardTitle: "Supplement Tracker",
        addSupplementButton: "Add Supplement",
        tableHeaderName: "Name",
        tableHeaderTiming: "When",
        tableHeaderQuantity: "Quantity",
        tableHeaderFrequency: "Frequency",
        tableHeaderTime: "Time",
        tableHeaderNotifications: "Notify",
        dialogEditTitle: "Edit Supplement",
        dialogAddTitle: "Add New Supplement",
        dialogDescription: "Fill in the details for your supplement.",
        formNameLabel: "Name",
        formTimingLabel: "When to take (e.g., Morning, Post-workout)",
        formQuantityLabel: "Quantity (e.g., 1 scoop, 2 pills)",
        formFrequencyLabel: "Frequency",
        selectFrequencyPlaceholder: "Select frequency",
        frequencyDaily: "Daily",
        frequencyWeekly: "Weekly",
        frequencyMonthly: "Monthly",
        frequencyCustom: "Custom",
        formTimeLabel: "Specific Time (HH:MM, optional)",
        enableNotificationForSupplement: "Enable notification for this supplement",
        toastAddedTitle: "Supplement Added",
        toastUpdatedTitle: "Supplement Updated",
        toastDeletedTitle: "Supplement Deleted",
        errorAllFieldsRequired: "Name, timing, and quantity are required.",
        noSupplementsAdded: "No supplements added yet. Click \"Add Supplement\" to start tracking.",
        enableAllNotificationsLabel: "All Notifications",
        enableAllNotificationsAria: "Toggle all supplement notifications",
        enableNotificationAria: "Enable notification for {name}",
        disableNotificationAria: "Disable notification for {name}",
    }
  },
  it: {
    nav: {
      home: 'Home', 
      exercises: 'Esercizi',
      workoutPlans: 'Schede', 
      calendar: 'Calendario',
      progress: 'Progressi',
      diet: 'Dieta',
    },
    userDropdown: {
      myAccount: 'Il Mio Account',
      settings: 'Impostazioni',
      logout: 'Esci',
    },
    header: {
      toggleTheme: 'Cambia tema',
      openMenu: 'Apri menu',
    },
    dashboard: {
      welcomeTitle: 'Benvenuto in SickFit Pro!',
      welcomeDescription: 'Il tuo viaggio verso la forma fisica ottimale inizia qui. Mettiamoci al lavoro.',
      workoutsThisWeek: 'Allenamenti Settimanali',
      weightLifted: 'Peso Totale Sollevato',
      currentWeight: 'Peso Attuale',
      logNewWorkout: 'Inizia Allenamento',
      todaysFocus: "Focus di Oggi",
      todaysFocusDescription: "Cosa c'è in programma per oggi?",
      checkCalendarForWorkout: "Controlla il calendario per l'allenamento di oggi!",
      viewCalendarToSeeWorkout: "Il tuo allenamento programmato apparirà qui.",
      viewFullSchedule: 'Visualizza Programma Completo',
      activityAndHistoryTitle: "Attività e Cronologia",
      noWorkoutHistory: "Nessuno storico allenamenti ancora. Completa un allenamento per vederlo qui!",
      viewAllHistoryButton: "Visualizza Tutto lo Storico",
      todayIsRestDay: "Oggi è giorno di riposo! Goditelo! 😊",
      noWorkoutScheduledForToday: "Nessun allenamento programmato per oggi.",
    },
    waterIntakeCard: {
      title: "Apporto Idrico",
      currentIntakeLabel: "Attuale: {current}ml / {dailyGoal}ml",
      setDailyGoalLabel: "Obiettivo Giornaliero (ml)",
      saveGoalButton: "Salva Obiettivo",
      goalSavedTitle: "Obiettivo Salvato",
      goalSavedDescription: "Il tuo obiettivo di apporto idrico giornaliero è stato aggiornato.",
      errorInvalidGoal: "Inserisci un obiettivo valido.",
      resetWaterButton: "Resetta Acqua",
      waterResetTitle: "Apporto Idrico Azzerato",
      waterResetDescription: "Il tuo apporto idrico giornaliero è stato azzerato.",
      goalSettingsButtonLabel: "Impostazioni Obiettivo", 
      goalSettingsAriaLabel: "Impostazioni Obiettivo Idrico", 
      goalSettingsTooltip: "Imposta il tuo obiettivo idrico giornaliero", 
      ariaAddGlass: "Aggiungi bicchiere ({amount}ml)",
      ariaAddBottle: "Aggiungi bottiglia ({amount}ml)",
      tooltipAddAmount: "+{amount}ml",
      reminderLabel: "Promemoria Idratazione",
      selectReminderFrequencyPlaceholder: "Imposta frequenza promemoria",
      reminderOff: "Spento",
      reminderDaily: "Giornaliero",
      reminderHourly: "Ogni ora",
      hydrationReminderSettingsAriaLabel: "Impostazioni Promemoria Idratazione",
      hydrationReminderTooltip: "Imposta promemoria idratazione",
    },
    macroTrackingCard: {
        title: "Monitoraggio Macro",
        proteinLabel: "Proteine",
        carbsLabel: "Carboidrati",
        fatLabel: "Grassi",
        setYourWeeklyGoals: "Imposta i Tuoi Obiettivi Macro Settimanali",
        selectDay: "Seleziona Giorno",
        saveGoalsButton: "Salva Obiettivi del Giorno",
        goalsSavedTitle: "Obiettivi Macro Salvati",
        goalsForDaySaved: "Obiettivi per {dayOfWeek} salvati con successo!",
        monthlyTotalsTitle: "Totali Mensili Stimati",
        totalProteinMonth: "Proteine Totali (Mese)",
        totalCarbsMonth: "Carboidrati Totali (Mese)",
        totalFatMonth: "Grassi Totali (Mese)",
        unitGrams: "g",
        loadingTotals: "Calcolo totali mensili...",
        macroTrendChartTitle: "Andamento Obiettivi Macronutrienti",
        dailyTab: "Giornaliero",
        weeklyTab: "Settimanale",
        monthlyTab: "Mensile",
        weekLabel: "Sett. {weekNum}",
        macroReminderSettingsAriaLabel: "Impostazioni promemoria macro",
        macroReminderTooltip: "Imposta promemoria monitoraggio macro",
        goalSettingsButtonAriaLabel: "Impostazioni Obiettivi Macro", 
        goalSettingsTooltip: "Imposta gli obiettivi macro settimanali", 
    },
     aiHealthAdvisor: {
        cardTitle: "Consulente Salute AI",
        dataUsageInfo: "I tuoi obiettivi macro, l'obiettivo di assunzione di acqua, le misurazioni corporee e il riepilogo degli allenamenti memorizzati verranno utilizzati automaticamente dall'AI per fornire consigli più personalizzati. Puoi anche porre una domanda specifica qui sotto.",
        userQueryLabel: "La Tua Domanda Specifica (Opzionale)",
        userQueryPlaceholder: "es. Come posso migliorare il sonno? o Quali sono degli esercizi per il mal di schiena?",
        userQueryDescription: "Poni una domanda specifica o lascia vuoto per consigli generali basati sui tuoi dati.",
        userQueryMinError: "Se poni una domanda, fornisci almeno 10 caratteri.",
        getAdviceButton: "Ottieni Consulenza Salute AI",
        adviceReadyTitle: "Consulenza Salute Pronta!",
        adviceReadyDescription: "L'AI ha generato una consulenza sulla salute per te.",
        errorTitle: "Errore Consulente",
        errorDescription: "Impossibile ottenere la consulenza sulla salute AI. Riprova.",
        resultsTitle: "Risultati Consulente Salute AI",
        overallAssessment: "Valutazione Generale",
        specificAdvice: "Consigli Specifici",
    },
    settingsPage: {
      title: 'Impostazioni',
      language: 'Lingua',
      selectLanguage: 'Seleziona lingua',
      english: 'English (US)',
      italian: 'Italiano (Italian)',
      spanish: 'Español (Spanish)',
      french: 'Français (French)',
      notifications: 'Notifiche',
      allNotificationsLabel: 'Abilita Tutte le Notifiche dell\'App',
      saveChanges: 'Salva Modifiche',
      settingsSaved: 'Impostazioni Salvate',
      preferencesUpdated: 'Le tue preferenze sono state aggiornate',
      profileInformationTitle: 'Informazioni Profilo',
      uploadProfilePictureLabel: 'Immagine Profilo',
      profilePictureAlt: 'Immagine del Profilo',
      photoSizeError: 'La dimensione della foto non deve superare i 2MB.',
      photoSizeLimit: 'Max 2MB. Formato quadrato consigliato.',
      nameLabel: 'Nome',
      namePlaceholder: 'Inserisci il tuo nome',
      emailLabel: 'Email',
      emailCannotBeChanged: 'L\'email non può essere modificata qui.',
      accountSecurityTitle: 'Sicurezza Account',
      currentPasswordLabel: 'Password Attuale',
      newPasswordLabel: 'Nuova Password',
      newPasswordPlaceholder: 'Inserisci nuova password (min. 8 caratteri)',
      confirmNewPasswordLabel: 'Conferma Nuova Password',
      confirmNewPasswordPlaceholder: 'Conferma nuova password',
      passwordMismatchError: 'Le nuove password non coincidono.',
      passwordChangedTitle: 'Password Modificata',
      passwordChangedSuccess: 'La tua password è stata aggiornata con successo.',
      currentPasswordRequiredError: 'La password attuale è richiesta per impostarne una nuova.',
      noChangesMadeTitle: 'Nessuna Modifica',
      noChangesMadeDescription: 'Nessuna impostazione è stata modificata.',
      toastErrorTitle: 'Errore',
      showPassword: 'Mostra password',
      hidePassword: 'Nascondi password',
      currentWeightLabel: 'Peso Attuale (kg)',
      currentWeightPlaceholder: 'es. 70.5',
    },
    aiSplitForm: { 
        cardTitle: "Consulente Fitness AI",
        generateAdviceButton: "Genera Consiglio",
        generatingSplitTitle: "Sto generando il tuo consiglio...",
        generatingSplitDescription: "La nostra AI sta elaborando. Potrebbe volerci un momento.",
        yourSuggestedAdviceTitle: "Il Tuo Consiglio dal Coach AI",
        suggestedKeyPointsLabel: "Suggerimenti Chiave:",
        detailedAnalysisLabel: "Analisi Dettagliata e Consigli:",
        toastSuggestionReadyTitle: "Consiglio Pronto!",
        toastSuggestionReadyDescription: "L'AI ha generato un consiglio di allenamento per te.",
        toastErrorTitle: "Errore",
        toastErrorDescription: "Impossibile ottenere il consiglio AI. Riprova.",
        errorFetchingHistory: "Impossibile recuperare automaticamente il tuo storico allenamenti. Assicurati di avere degli allenamenti registrati.",
        noHistoryForAdvice: "Nessuno storico allenamenti disponibile per generare consigli.",
        genericGoalForAdvice: "Miglioramento generale basato sullo storico allenamenti e sui dati di progresso.",
        promptGenerateAdvice: "Clicca il pulsante qui sopra per generare un consiglio di allenamento personalizzato basato sui tuoi dati di progresso."
    },
    calendarPage: {
        title: "Calendario Allenamenti",
        description: "Pianifica e monitora il tuo programma di allenamento settimanale.",
        selectADate: "Seleziona una Data",
        workoutsScheduledForThisDay: "Allenamenti programmati per questo giorno.",
        addWorkoutToDay: "Aggiungi Allenamento",
        noWorkoutsScheduled: "Nessun allenamento programmato per questo giorno.",
        selectDateToSeeWorkouts: "Seleziona una data per vedere gli allenamenti programmati.",
        dialogAddWorkoutTitle: "Aggiungi Allenamento a {dayOfWeek}",
        dialogAddWorkoutDescription: "Seleziona una scheda di allenamento da programmare per questo giorno della settimana.",
        workoutPlanLabel: "Scheda Allenamento",
        selectAPlanPlaceholder: "Seleziona una scheda",
        samplePlan1: "Scheda Total Body",
        samplePlan2: "Scheda Parte Superiore",
        samplePlan3: "Scheda Gambe Intensa",
        samplePlan4: "Sessione Cardio",
        cancelButton: "Annulla",
        scheduleWorkoutButton: "Programma Allenamento",
        loadingCalendar: "Caricamento calendario...",
        weeklyScheduleTitle: "Programma Allenamento Settimanale",
        weeklyScheduleDescription: "Imposta la tua settimana di allenamento tipo. Questo programma si ripeterà automaticamente.",
        days: {
          monday: "Lunedì",
          tuesday: "Martedì",
          wednesday: "Mercoledì",
          thursday: "Giovedì",
          friday: "Venerdì",
          saturday: "Sabato",
          sunday: "Domenica",
        },
        noWorkoutsForDayOfWeek: "Nessun allenamento programmato per {dayOfWeek}.",
        addWorkoutTo: "Aggiungi a {dayOfWeek}",
        toastWorkoutScheduledTitle: "Allenamento Programmato!",
        toastWorkoutScheduledDescriptionNoTime: "{planName} il {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Allenamento Rimosso",
        errorSelectDayAndPlan: "Seleziona un giorno e una scheda di allenamento.",
        errorPlanNotFound: "Scheda selezionata non trovata.",
    },
    exercisesPage: {
        title: "Esercizi Personalizzati",
        description: "Gestisci la tua libreria di esercizi personalizzati.",
        addNewExerciseButton: "Aggiungi Nuovo Esercizio",
        yourExercisesCardTitle: "I Tuoi Esercizi",
        tableHeaderName: "Nome",
        tableHeaderMuscleGroup: "Gruppo Muscolare",
        tableHeaderType: "Tipo",
        tableHeaderActions: "Azioni",
        dialogAddTitle: "Aggiungi Nuovo Esercizio",
        dialogAddDescription: "Inserisci i dettagli per il tuo nuovo esercizio.",
        dialogEditTitle: "Modifica Esercizio",
        dialogEditDescription: "Aggiorna i dettagli del tuo esercizio.",
        formNameLabel: "Nome",
        formDescriptionLabel: "Descrizione",
        formMuscleGroupLabel: "Gruppo Muscolare",
        selectMuscleGroupPlaceholder: "Seleziona gruppo muscolare",
        muscleGroupChest: "Petto",
        muscleGroupBack: "Schiena",
        muscleGroupLegs: "Gambe",
        muscleGroupShoulders: "Spalle",
        muscleGroupBiceps: "Bicipiti",
        muscleGroupTriceps: "Tricipiti",
        muscleGroupAbs: "Addominali",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Altro",
        formTypeLabel: "Tipo",
        selectExerciseTypePlaceholder: "Seleziona tipo di esercizio",
        typeStrength: "Forza",
        typeCardio: "Cardio",
        typeFlexibility: "Flessibilità",
        typePlyometrics: "Pliometria",
        typeOther: "Altro",
        cancelButton: "Annulla",
        saveExerciseButton: "Salva Esercizio",
    },
    progressPage: {
        title: "Monitoraggio Progressi",
        description: "Visualizza il tuo percorso di fitness e celebra i tuoi traguardi.",
        performanceMetricsCardTitle: "Metriche di Performance",
        bodyCompositionCardTitle: "Composizione Corporea",
        weightLabel: "Peso (kg)",
        photoComparisonCardTitle: "Confronto Foto",
        beforePhotoLabel: "Foto Prima",
        afterPhotoLabel: "Foto Dopo",
        noPhotoUploaded: "Nessuna foto caricata",
        clickToUpload: "Clicca per caricare",
        uploadButtonLabel: "Carica",
        bodyMeasurementsCardTitle: "Misure Corporee",
        addMeasurementButton: "Aggiungi Misura",
        measurementDialogAddTitle: "Aggiungi Nuova Misura",
        measurementDialogEditTitle: "Modifica Misura",
        measurementDialogDescription: "Inserisci i dettagli per la tua misurazione.",
        formDateLabel: "Data",
        formMeasurementNameLabel: "Tipo Misurazione",
        selectMeasurementNamePlaceholder: "Seleziona tipo misurazione",
        measurementNameBiceps: "Bicipiti",
        measurementNameChest: "Petto",
        measurementNameWaist: "Vita",
        measurementNameHips: "Fianchi",
        measurementNameThigh: "Coscia",
        measurementNameCalf: "Polpaccio",
        measurementNameWeight: "Peso",
        measurementNameHeight: "Altezza",
        formValueLabel: "Valore",
        formUnitLabel: "Unità",
        unitCM: "cm",
        unitIN: "pollici",
        unitKG: "kg",
        unitLBS: "libbre",
        formNotesLabel: "Note",
        formNotesPlaceholder: "Inserisci eventuali note pertinenti...",
        saveMeasurementButton: "Salva Misura",
        tableHeaderDate: "Data",
        tableHeaderMeasurementName: "Misurazione",
        tableHeaderValue: "Valore",
        measurementReminderLabel: "Promemoria Misurazioni",
        selectReminderFrequencyPlaceholder: "Seleziona frequenza promemoria",
        reminderOff: "Spento",
        reminderDaily: "Giornaliero",
        reminderWeekly: "Settimanale",
        reminderBiWeekly: "Bisettimanale",
        reminderMonthly: "Mensile",
        measurementSaved: "Misura Salvata",
        measurementDeleted: "Misura Eliminata",
        noMeasurementsYet: "Nessuna misura registrata. Aggiungi la prima!",
        formValidationAlert: "Compila data, tipo misurazione e valore.",
        timeRangeWeekly: "Settimanale",
        timeRangeMonthly: "Mensile",
        timeRangeYearly: "Annuale",
        muscleGroupChestChart: "Petto (Volume)",
        muscleGroupBackChart: "Schiena (Volume)",
        muscleGroupLegsChart: "Gambe (Volume)",
        muscleGroupShouldersChart: "Spalle (Volume)",
        muscleGroupBicepsChart: "Bicipiti (Volume)",
        muscleGroupTricepsChart: "Tricipiti (Volume)",
        weekShortLabel: "S{num}",
        weeklyTrainingVolumeLabel: "Volume Allenamento",
    },
     workoutPlansPage: {
        title: "Schede Allenamento",
        description: "Crea, gestisci e condividi i tuoi programmi di allenamento.",
        createNewPlanButton: "Crea Nuova Scheda",
        estDurationLabel: "Durata Stimata",
        exercisesLabel: "Esercizi",
        involvedMusclesLabel: "Muscoli Coinvolti:",
        startButton: "Inizia",
        dialogEditTitle: "Modifica Scheda Allenamento",
        dialogEditDescription: "Aggiorna i dettagli della tua scheda di allenamento.",
        dialogCreateTitle: "Crea Nuova Scheda Allenamento",
        dialogCreateDescription: "Progetta la tua nuova scheda di allenamento.",
        planNameLabel: "Nome Scheda",
        descriptionLabel: "Descrizione",
        exerciseNameLabel: "Nome Esercizio",
        setsLabel: "Serie",
        repsLabel: "Ripetizioni",
        addThisExerciseButton: "Aggiungi Esercizio",
        addedExercisesLabel: "Esercizi Aggiunti:",
        noExercisesAddedYet: "Nessun esercizio aggiunto a questa scheda.",
        exerciseSelectionPlaceholder: "Aggiungi esercizi a questa scheda usando il modulo sopra.",
        addExerciseButton: "Aggiungi Esercizio alla Scheda",
        cancelButton: "Annulla",
        savePlanButton: "Salva Scheda",
        toastPlanUpdatedTitle: "Scheda Aggiornata",
        toastPlanUpdatedDescription: "La scheda \"{planName}\" è stata aggiornata.",
        toastPlanCreatedTitle: "Scheda Creata",
        toastPlanCreatedDescription: "La scheda \"{planName}\" è stata creata.",
        toastPlanDeletedTitle: "Scheda Eliminata",
        toastPlanDeletedDescription: "La scheda \"{planName}\" è stata eliminata.",
        toastLinkCopiedTitle: "Link Copiato!",
        toastLinkCopiedDescription: "Link della scheda di allenamento copiato negli appunti.",
        muscleSilhouetteAlt: "Gruppi muscolari coinvolti nella scheda",
        noMuscleGroupsSpecified: "N/D"
    },
    startWorkoutPage: {
      title: "Inizia Nuovo Allenamento",
      description: "Scegli una scheda da iniziare o avvia una sessione libera.",
      selectPlanTitle: "Seleziona una Scheda",
      noPlansAvailable: "Nessuna scheda di allenamento disponibile. Creane una prima!",
      startPlanButton: "Inizia Scheda",
    },
    activeWorkoutPage: {
      title: "Allenamento Attivo: {planName}",
      description: "Traccia serie, ripetizioni e pesi per questa sessione.",
      finishWorkoutButton: "Termina Allenamento",
      logSetButton: "Registra Serie",
      planNotFound: "Scheda di allenamento non trovata.",
      planNotFoundDescription: "Controlla l'URL o torna indietro per selezionare una scheda valida.",
      loadingWorkout: "Caricamento Allenamento...",
      loadingDescription: "Attendere prego, stiamo caricando i dettagli della scheda.",
      targetSetsLabel: "Serie Obiettivo",
      targetRepsLabel: "Ripetizioni Obiettivo",
      repsInputLabel: "Ripetizioni",
      weightInputLabel: "Peso (kg)",
      setColumnLabel: "Serie",
      dateColumnLabel: "Data",
      repsColumnLabel: "Ripetizioni",
      weightColumnLabel: "Peso (kg)",
      toastSetLoggedTitle: "Serie Registrata",
      toastSetLoggedDescription: "Serie per {exerciseName} registrata.",
      toastSetDeletedTitle: "Serie Eliminata",
      toastWorkoutFinishedTitle: "Allenamento Terminato!",
      toastWorkoutFinishedDescription: "Ottimo lavoro! Hai completato l'allenamento in {duration}!",
      overallProgressLabel: "Progresso Allenamento Complessivo",
      setCompletionLabel: "Serie: {completed}/{total}",
      noGifAvailable: "Nessun GIF disponibile",
      exerciseDemoAlt: "dimostrazione esercizio",
      nextExerciseButton: "Prossimo Esercizio",
      completeWorkoutButton: "Completa Allenamento",
      workoutCompleteTitle: "Allenamento Completato!",
      workoutCompleteDescription: "Hai completato con successo l'allenamento {planName}.",
      totalTimeLabel: "Tempo Totale",
      backToDashboardButton: "Torna alla Home",
      confirmFinishTitle: "Terminare Allenamento?",
      confirmFinishDescription: "Sei sicuro di voler contrassegnare questo allenamento come completato?",
      confirmFinishButton: "Sì, Termina",
      noSetsLoggedYet: "Nessuna serie registrata per questo esercizio.",
      sessionPBsLabel: "PB Sessione",
      maxWeightLabel: "Peso Max",
      maxRepsLabel: "Rip. Max",
      repsUnitLabel: "rip.",
      workoutInProgressTitle: "Allenamento in Corso",
      finishCurrentWorkoutPrompt: "Hai un allenamento attivo. Per favore, terminalo o abbandonalo prima di iniziarne uno nuovo o creare/modificare schede.",
    },
    dietPage: {
        title: "Monitoraggio Dieta",
        description: "Gestisci il tuo apporto nutrizionale giornaliero e l'idratazione.",
    },
    toastErrorTitle: "Errore",
    resumeWorkoutButton: {
      resumeTitle: "Riprendi Allenamento",
      resume: "Riprendi: {planName}",
    },
    supplements: {
        cardTitle: "Monitoraggio Integratori",
        addSupplementButton: "Aggiungi Integratore",
        tableHeaderName: "Nome",
        tableHeaderTiming: "Quando",
        tableHeaderQuantity: "Quantità",
        tableHeaderFrequency: "Cadenza",
        tableHeaderTime: "Orario",
        tableHeaderNotifications: "Notifica",
        dialogEditTitle: "Modifica Integratore",
        dialogAddTitle: "Aggiungi Nuovo Integratore",
        dialogDescription: "Inserisci i dettagli del tuo integratore.",
        formNameLabel: "Nome",
        formTimingLabel: "Quando assumerlo (es. Mattina, Post-allenamento)",
        formQuantityLabel: "Quantità (es. 1 misurino, 2 compresse)",
        formFrequencyLabel: "Cadenza",
        selectFrequencyPlaceholder: "Seleziona cadenza",
        frequencyDaily: "Giornaliera",
        frequencyWeekly: "Settimanale",
        frequencyMonthly: "Mensile",
        frequencyCustom: "Personalizzata",
        formTimeLabel: "Orario Specifico (HH:MM, opzionale)",
        enableNotificationForSupplement: "Abilita notifica per questo integratore",
        toastAddedTitle: "Integratore Aggiunto",
        toastUpdatedTitle: "Integratore Aggiornato",
        toastDeletedTitle: "Integratore Eliminato",
        errorAllFieldsRequired: "Nome, quando e quantità sono obbligatori.",
        noSupplementsAdded: "Nessun integratore aggiunto. Clicca \"Aggiungi Integratore\" per iniziare.",
        enableAllNotificationsLabel: "Tutte le Notifiche",
        enableAllNotificationsAria: "Attiva/disattiva tutte le notifiche degli integratori",
        enableNotificationAria: "Abilita notifica per {name}",
        disableNotificationAria: "Disabilita notifica per {name}",
    }
  },
  es: { 
    nav: {
      home: 'Inicio',
      exercises: 'Ejercicios',
      workoutPlans: 'Planes de Entrenamiento',
      calendar: 'Calendario',
      progress: 'Progreso',
      diet: 'Dieta',
    },
    userDropdown: {
        myAccount: 'Mi Cuenta',
        settings: 'Configuración',
        logout: 'Cerrar Sesión',
    },
    header: {
        toggleTheme: 'Cambiar tema',
        openMenu: 'Abrir menú',
    },
     dashboard: {
      welcomeTitle: '¡Bienvenido a SickFit Pro!',
      welcomeDescription: "Tu viaje hacia la máxima forma física comienza aquí. ¡Manos a la obra!",
      workoutsThisWeek: 'Entrenamientos Esta Semana',
      weightLifted: 'Peso Total Levantado',
      currentWeight: 'Peso Actual',
      logNewWorkout: 'Empezar Entrenamiento',
      todaysFocus: "Enfoque de Hoy",
      todaysFocusDescription: "¿Qué hay en la agenda para hoy?",
      checkCalendarForWorkout: "¡Revisa tu calendario para el entrenamiento de hoy!",
      viewCalendarToSeeWorkout: "Tu entrenamiento programado aparecerá aquí.",
      viewFullSchedule: 'Ver Horario Completo',
      activityAndHistoryTitle: "Actividad e Historial",
      noWorkoutHistory: "Aún no hay historial de entrenamientos. ¡Completa un entrenamiento para verlo aquí!",
      viewAllHistoryButton: "Ver Todo el Historial",
      todayIsRestDay: "¡Hoy es día de descanso! ¡Disfrútalo! 😊",
      noWorkoutScheduledForToday: "Ningún entrenamiento programado para hoy.",
    },
    settingsPage: {
      title: 'Configuración',
      language: 'Idioma',
      selectLanguage: 'Seleccionar idioma',
      english: 'Inglés (EE. UU.)',
      italian: 'Italiano',
      spanish: 'Español',
      french: 'Francés',
      notifications: 'Notificaciones',
      allNotificationsLabel: 'Habilitar Todas las Notificaciones de la App',
      saveChanges: 'Guardar Cambios',
      settingsSaved: 'Configuración Guardada',
      preferencesUpdated: 'Tus preferencias han sido actualizadas',
      profileInformationTitle: 'Información del Perfil',
      uploadProfilePictureLabel: 'Foto de Perfil',
      profilePictureAlt: 'Foto de Perfil',
      photoSizeError: 'El tamaño de la foto no debe exceder los 2MB.',
      photoSizeLimit: 'Máx 2MB. Se recomienda relación de aspecto cuadrada.',
      nameLabel: 'Nombre',
      namePlaceholder: 'Introduce tu nombre',
      emailLabel: 'Correo Electrónico',
      emailCannotBeChanged: 'El correo electrónico no se puede cambiar aquí.',
      accountSecurityTitle: 'Seguridad de la Cuenta',
      currentPasswordLabel: 'Contraseña Actual',
      newPasswordLabel: 'Nueva Contraseña',
      newPasswordPlaceholder: 'Introduce nueva contraseña (mín. 8 caracteres)',
      confirmNewPasswordLabel: 'Confirmar Nueva Contraseña',
      confirmNewPasswordPlaceholder: 'Confirma la nueva contraseña',
      passwordMismatchError: 'Las nuevas contraseñas no coinciden.',
      passwordChangedTitle: 'Contraseña Cambiada',
      passwordChangedSuccess: 'Tu contraseña ha sido actualizada correctamente.',
      currentPasswordRequiredError: 'Se requiere la contraseña actual para establecer una nueva.',
      noChangesMadeTitle: 'Sin Cambios',
      noChangesMadeDescription: 'No se modificó ninguna configuración.',
      toastErrorTitle: 'Error',
      showPassword: 'Mostrar contraseña',
      hidePassword: 'Ocultar contraseña',
      currentWeightLabel: 'Peso Actual (kg)',
      currentWeightPlaceholder: 'ej. 70.5',
    },
    toastErrorTitle: "Error",
    waterIntakeCard: {
      title: "Consumo de Agua",
      currentIntakeLabel: "Actual: {current}ml / {dailyGoal}ml",
      setDailyGoalLabel: "Meta Diaria (ml)",
      saveGoalButton: "Guardar Meta",
      reminderLabel: "Recordatorio de Hidratación",
      selectReminderFrequencyPlaceholder: "Frecuencia",
      reminderOff: "Apagado",
      reminderDaily: "Diario",
      reminderHourly: "Cada Hora",
       goalSavedTitle: "Meta Guardada",
      goalSavedDescription: "Tu meta diaria de consumo de agua ha sido actualizada.",
      errorInvalidGoal: "Por favor, introduce una meta válida.",
      resetWaterButton: "Reiniciar Agua",
      waterResetTitle: "Agua Reiniciada",
      waterResetDescription: "Tu consumo de agua para el día ha sido reiniciado.",
      goalSettingsButtonLabel: "Establecer Meta Diaria",
      goalSettingsAriaLabel: "Configuración de Meta de Agua", 
      goalSettingsTooltip: "Establece tu meta diaria de consumo de agua",
      ariaAddGlass: "Añadir vaso ({amount}ml)",
      ariaAddBottle: "Añadir botella ({amount}ml)",
      tooltipAddAmount: "+{amount}ml",
      hydrationReminderSettingsAriaLabel: "Configuración de Recordatorio de Hidratación",
      hydrationReminderTooltip: "Establecer recordatorio de hidratación",
    },
    macroTrackingCard: {
        title: "Seguimiento de Macros",
        proteinLabel: "Proteína",
        carbsLabel: "Carbohidratos",
        fatLabel: "Grasa",
        setYourWeeklyGoals: "Establece Tus Metas Semanales de Macros",
        selectDay: "Seleccionar Día",
        saveGoalsButton: "Guardar Metas del Día",
        monthlyTotalsTitle: "Totales Mensuales Estimados",
        totalProteinMonth: "Proteína Total (Mes)",
        totalCarbsMonth: "Carbohidratos Totales (Mes)",
        totalFatMonth: "Grasa Total (Mes)",
        unitGrams: "g",
        loadingTotals: "Calculando totales mensuales...",
         goalsSavedTitle: "Metas de Macros Guardadas",
        goalsForDaySaved: "¡Metas para {dayOfWeek} guardadas con éxito!",
        macroTrendChartTitle: "Tendencias de Metas de Macronutrientes",
        dailyTab: "Diario",
        weeklyTab: "Semanal",
        monthlyTab: "Mensual",
        weekLabel: "Semana {weekNum}",
        macroReminderSettingsAriaLabel: "Configuración de recordatorio de macros",
        macroReminderTooltip: "Establecer recordatorio de registro de macros",
        goalSettingsButtonAriaLabel: "Configuración de Metas de Macros",
        goalSettingsTooltip: "Establecer metas semanales de macronutrientes",
    },
    aiHealthAdvisor: {
        cardTitle: "Asesor de Salud IA",
        dataUsageInfo: "Tus metas de macronutrientes, meta de ingesta de agua, mediciones corporales y resumen de entrenamiento almacenados se utilizarán automáticamente por la IA para proporcionar consejos más personalizados. También puedes hacer una pregunta específica a continuación.",
        userQueryLabel: "Tu Pregunta Específica (Opcional)",
        userQueryPlaceholder: "Ej: ¿Cómo puedo mejorar mi sueño? o ¿Cuáles son buenos ejercicios para el dolor lumbar?",
        userQueryDescription: "Haz una pregunta específica o déjalo en blanco para obtener consejos generales basados en tus datos.",
        userQueryMinError: "Si haces una pregunta, proporciona al menos 10 caracteres.",
        getAdviceButton: "Obtener Consejo de Salud IA",
        adviceReadyTitle: "¡Consejo de Salud Listo!",
        adviceReadyDescription: "La IA ha generado consejos de salud para ti.",
        errorTitle: "Error del Asesor",
        errorDescription: "Error al obtener el consejo de salud de la IA. Inténtalo de nuevo.",
        resultsTitle: "Resultados del Asesor de Salud IA",
        overallAssessment: "Evaluación General",
        specificAdvice: "Consejos Específicos",
    },
    dietPage: {
        title: "Seguimiento de Dieta",
        description: "Gestiona tu ingesta nutricional diaria y tu hidratación.",
    },
    aiSplitForm: {
        cardTitle: "Asesor Fitness IA",
        generateAdviceButton: "Generar Consejo",
        generatingSplitTitle: "Generando tu consejo...",
        generatingSplitDescription: "Nuestra IA está pensando. Esto podría tomar un momento.",
        yourSuggestedAdviceTitle: "Tu Consejo de Fitness IA",
        suggestedKeyPointsLabel: "Sugerencias Clave:",
        detailedAnalysisLabel: "Análisis Detallado y Consejos:",
        toastSuggestionReadyTitle: "¡Consejo Listo!",
        toastSuggestionReadyDescription: "La IA ha generado consejos de entrenamiento para ti.",
        toastErrorTitle: "Error",
        toastErrorDescription: "Error al obtener el consejo de la IA. Inténtalo de nuevo.",
        errorFetchingHistory: "No se pudo recuperar automáticamente tu historial de entrenamiento. Asegúrate de tener algunos entrenamientos registrados.",
        noHistoryForAdvice: "No hay historial de entrenamiento disponible para generar consejos.",
        genericGoalForAdvice: "Mejora general basada en el historial de entrenamiento y los datos de progreso.",
        promptGenerateAdvice: "Haz clic en el botón de arriba para generar consejos de entrenamiento personalizados basados en tus datos de progreso."
    },
    calendarPage: {
        title: "Calendario de Entrenamientos",
        description: "Planifica y sigue tu horario de entrenamiento semanal.",
        weeklyScheduleTitle: "Horario Semanal de Entrenamiento",
        weeklyScheduleDescription: "Configura tu semana de entrenamiento típica. Este horario se repetirá automáticamente.",
        days: {
          monday: "Lunes",
          tuesday: "Martes",
          wednesday: "Miércoles",
          thursday: "Jueves",
          friday: "Viernes",
          saturday: "Sábado",
          sunday: "Domingo",
        },
        noWorkoutsForDayOfWeek: "No hay entrenamientos programados para {dayOfWeek}.",
        addWorkoutToDay: "Añadir Entrenamiento",
        cancelButton: "Cancelar",
        scheduleWorkoutButton: "Programar Entrenamiento",
        workoutPlanLabel: "Plan de Entrenamiento",
        selectAPlanPlaceholder: "Selecciona un plan",
        dialogAddWorkoutTitle: "Añadir Entrenamiento a {dayOfWeek}",
        dialogAddWorkoutDescription: "Selecciona un plan de entrenamiento para programar para este día de la semana.",
        toastWorkoutScheduledTitle: "¡Entrenamiento Programado!",
        toastWorkoutScheduledDescriptionNoTime: "{planName} el {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Entrenamiento Eliminado",
        errorSelectDayAndPlan: "Por favor, selecciona un día y un plan de entrenamiento.",
        errorPlanNotFound: "Plan seleccionado no encontrado.",
        samplePlan1: "Explosión de Cuerpo Completo",
        samplePlan2: "Poder del Tren Superior",
        samplePlan3: "Dominación del Día de Piernas",
        samplePlan4: "Sesión de Cardio",
        loadingCalendar: "Cargando calendario...",
    },
     exercisesPage: {
        title: "Ejercicios Personalizados",
        description: "Gestiona tu biblioteca de ejercicios personalizados.",
        addNewExerciseButton: "Añadir Nuevo Ejercicio",
        yourExercisesCardTitle: "Tus Ejercicios",
        tableHeaderName: "Nombre",
        tableHeaderMuscleGroup: "Grupo Muscular",
        tableHeaderType: "Tipo",
        tableHeaderActions: "Acciones",
        dialogAddTitle: "Añadir Nuevo Ejercicio",
        dialogAddDescription: "Completa los detalles de tu nuevo ejercicio.",
        dialogEditTitle: "Editar Ejercicio",
        dialogEditDescription: "Actualiza los detalles de tu ejercicio.",
        formNameLabel: "Nombre",
        formDescriptionLabel: "Descripción",
        formMuscleGroupLabel: "Grupo Muscular",
        selectMuscleGroupPlaceholder: "Selecciona grupo muscular",
        muscleGroupChest: "Pecho",
        muscleGroupBack: "Espalda",
        muscleGroupLegs: "Piernas",
        muscleGroupShoulders: "Hombros",
        muscleGroupBiceps: "Bíceps",
        muscleGroupTriceps: "Tríceps",
        muscleGroupAbs: "Abdominales",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Otro",
        formTypeLabel: "Tipo",
        selectExerciseTypePlaceholder: "Selecciona tipo de ejercicio",
        typeStrength: "Fuerza",
        typeCardio: "Cardio",
        typeFlexibility: "Flexibilidad",
        typePlyometrics: "Pliométricos",
        typeOther: "Otro",
        cancelButton: "Cancelar",
        saveExerciseButton: "Guardar Ejercicio",
    },
    progressPage: {
        title: "Seguimiento de Progreso",
        description: "Visualiza tu viaje de fitness y celebra tus logros.",
        performanceMetricsCardTitle: "Métricas de Rendimiento",
        bodyCompositionCardTitle: "Composición Corporal",
        weightLabel: "Peso (kg)",
        photoComparisonCardTitle: "Comparación de Fotos",
        beforePhotoLabel: "Foto Antes",
        afterPhotoLabel: "Foto Después",
        noPhotoUploaded: "No se ha subido ninguna foto",
        clickToUpload: "Haz clic para subir",
        uploadButtonLabel: "Subir",
        bodyMeasurementsCardTitle: "Medidas Corporales",
        addMeasurementButton: "Añadir Medida",
        measurementDialogAddTitle: "Añadir Nueva Medida",
        measurementDialogEditTitle: "Editar Medida",
        measurementDialogDescription: "Introduce los detalles de tu medida.",
        formDateLabel: "Fecha",
        formMeasurementNameLabel: "Tipo de Medida",
        selectMeasurementNamePlaceholder: "Selecciona tipo de medida",
        measurementNameBiceps: "Bíceps",
        measurementNameChest: "Pecho",
        measurementNameWaist: "Cintura",
        measurementNameHips: "Caderas",
        measurementNameThigh: "Muslo",
        measurementNameCalf: "Pantorrilla",
        measurementNameWeight: "Peso",
        measurementNameHeight: "Altura",
        formValueLabel: "Valor",
        unitCM: "cm",
        unitIN: "pulgadas",
        unitKG: "kg",
        unitLBS: "libras",
        formNotesLabel: "Notas",
        formNotesPlaceholder: "Introduce notas relevantes...",
        saveMeasurementButton: "Guardar Medida",
        tableHeaderDate: "Fecha",
        tableHeaderMeasurementName: "Medida",
        tableHeaderValue: "Valor",
        measurementReminderLabel: "Recordatorio de Medidas",
        selectReminderFrequencyPlaceholder: "Selecciona frecuencia",
        reminderOff: "Desactivado",
        reminderDaily: "Diario",
        reminderWeekly: "Semanal",
        reminderBiWeekly: "Quincenal",
        reminderMonthly: "Mensual",
        measurementSaved: "Medida Guardada",
        measurementDeleted: "Medida Eliminada",
        noMeasurementsYet: "Aún no hay medidas registradas. ¡Añade la primera!",
        formValidationAlert: "Por favor, completa la fecha, el tipo de medida y el valor.",
        timeRangeWeekly: "Semanal",
        timeRangeMonthly: "Mensual",
        timeRangeYearly: "Anual",
        muscleGroupChestChart: "Pecho (Volumen)",
        muscleGroupBackChart: "Espalda (Volumen)",
        muscleGroupLegsChart: "Piernas (Volumen)",
        muscleGroupShouldersChart: "Hombros (Volumen)",
        muscleGroupBicepsChart: "Bíceps (Volumen)",
        muscleGroupTricepsChart: "Tríceps (Volumen)",
        weekShortLabel: "S{num}",
        weeklyTrainingVolumeLabel: "Volumen de Entrenamiento",
    },
    workoutPlansPage: {
        title: "Planes de Entrenamiento",
        description: "Crea, gestiona y comparte tus horarios de entrenamiento.",
        createNewPlanButton: "Crear Nuevo Plan",
        estDurationLabel: "Duración Estimada",
        exercisesLabel: "Ejercicios",
        involvedMusclesLabel: "Músculos Involucrados:",
        startButton: "Empezar",
        dialogEditTitle: "Editar Plan de Entrenamiento",
        dialogEditDescription: "Actualiza los detalles de tu plan de entrenamiento.",
        dialogCreateTitle: "Crear Nuevo Plan de Entrenamiento",
        dialogCreateDescription: "Diseña tu nuevo plan de entrenamiento.",
        planNameLabel: "Nombre del Plan",
        descriptionLabel: "Descripción",
        exerciseNameLabel: "Nombre del Ejercicio",
        setsLabel: "Series",
        repsLabel: "Repeticiones",
        addThisExerciseButton: "Añadir este Ejercicio",
        addedExercisesLabel: "Ejercicios Añadidos:",
        noExercisesAddedYet: "Aún no se han añadido ejercicios a este plan.",
        cancelButton: "Cancelar",
        savePlanButton: "Guardar Plan",
        toastPlanUpdatedTitle: "Plan Actualizado",
        toastPlanUpdatedDescription: '"{planName}" ha sido actualizado.',
        toastPlanCreatedTitle: "Plan Creado",
        toastPlanCreatedDescription: '"{planName}" ha sido creado.',
        toastPlanDeletedTitle: "Plan Eliminado",
        toastPlanDeletedDescription: '"{planName}" ha sido eliminado.',
        toastLinkCopiedTitle: "¡Enlace Copiado!",
        toastLinkCopiedDescription: "Enlace del plan de entrenamiento copiado al portapapeles.",
        muscleSilhouetteAlt: "Grupos musculares involucrados en el plan",
        noMuscleGroupsSpecified: "N/A"
    },
    startWorkoutPage: {
      title: "Empezar Nuevo Entrenamiento",
      description: "Elige un plan para empezar o inicia una sesión ad-hoc.",
      selectPlanTitle: "Selecciona un Plan",
      noPlansAvailable: "No hay planes de entrenamiento disponibles. ¡Crea uno primero!",
      startPlanButton: "Empezar Plan",
    },
    activeWorkoutPage: {
        title: "Entrenamiento Activo: {planName}",
        description: "Registra tus series, repeticiones y pesos para esta sesión.",
        finishWorkoutButton: "Finalizar Entrenamiento",
        logSetButton: "Registrar Serie",
        planNotFound: "Plan de entrenamiento no encontrado.",
        planNotFoundDescription: "Por favor, comprueba la URL o vuelve para seleccionar un plan válido.",
        loadingWorkout: "Cargando Entrenamiento...",
        loadingDescription: "Por favor, espera mientras cargamos los detalles del plan.",
        targetSetsLabel: "Series Objetivo",
        targetRepsLabel: "Repeticiones Objetivo",
        repsInputLabel: "Repeticiones",
        weightInputLabel: "Peso (kg)",
        setColumnLabel: "Serie",
        dateColumnLabel: "Fecha",
        repsColumnLabel: "Repeticiones",
        weightColumnLabel: "Peso (kg)",
        toastSetLoggedTitle: "Serie Registrada",
        toastSetLoggedDescription: "Serie para {exerciseName} registrada.",
        toastSetDeletedTitle: "Serie Eliminada",
        toastWorkoutFinishedTitle: "¡Entrenamiento Finalizado!",
        toastWorkoutFinishedDescription: "¡Buen trabajo completando tu entrenamiento en {duration}!",
        overallProgressLabel: "Progreso General del Entrenamiento",
        setCompletionLabel: "Series: {completed}/{total}",
        noGifAvailable: "No hay GIF disponible",
        exerciseDemoAlt: "demostración del ejercicio",
        completeWorkoutButton: "Completar Entrenamiento",
        workoutCompleteTitle: "¡Entrenamiento Completado!",
        workoutCompleteDescription: "Has completado con éxito el entrenamiento {planName}.",
        totalTimeLabel: "Tiempo Total",
        backToDashboardButton: "Volver al Inicio",
        confirmFinishTitle: "¿Finalizar Entrenamiento?",
        confirmFinishDescription: "¿Estás seguro de que quieres marcar este entrenamiento como completado?",
        confirmFinishButton: "Sí, Finalizar",
        noSetsLoggedYet: "Aún no hay series registradas para este ejercicio.",
        sessionPBsLabel: "RPs de Sesión",
        maxWeightLabel: "Peso Máx.",
        maxRepsLabel: "Rep. Máx.",
        repsUnitLabel: "reps",
        workoutInProgressTitle: "Entrenamiento en Curso",
        finishCurrentWorkoutPrompt: "Tienes un entrenamiento activo. Por favor, termínalo o abandónalo antes de empezar uno nuevo o crear/editar planes.",
    },
    resumeWorkoutButton: {
      resumeTitle: "Reanudar Entrenamiento",
      resume: "Reanudar: {planName}",
    },
    supplements: {
        cardTitle: "Seguimiento de Suplementos",
        addSupplementButton: "Añadir Suplemento",
        tableHeaderName: "Nombre",
        tableHeaderTiming: "Cuándo",
        tableHeaderQuantity: "Cantidad",
        tableHeaderFrequency: "Frecuencia",
        tableHeaderTime: "Hora",
        tableHeaderNotifications: "Notificar",
        dialogEditTitle: "Editar Suplemento",
        dialogAddTitle: "Añadir Nuevo Suplemento",
        dialogDescription: "Completa los detalles de tu suplemento.",
        formNameLabel: "Nombre",
        formTimingLabel: "Cuándo tomar (ej. Mañana, Post-entrenamiento)",
        formQuantityLabel: "Cantidad (ej. 1 scoop, 2 pastillas)",
        formFrequencyLabel: "Frecuencia",
        selectFrequencyPlaceholder: "Selecciona frecuencia",
        frequencyDaily: "Diaria",
        frequencyWeekly: "Semanal",
        frequencyMonthly: "Mensual",
        frequencyCustom: "Personalizada",
        formTimeLabel: "Hora Específica (HH:MM, opcional)",
        enableNotificationForSupplement: "Habilitar notificación para este suplemento",
        toastAddedTitle: "Suplemento Añadido",
        toastUpdatedTitle: "Suplemento Actualizado",
        toastDeletedTitle: "Suplemento Eliminado",
        errorAllFieldsRequired: "Nombre, cuándo y cantidad son obligatorios.",
        noSupplementsAdded: "Aún no hay suplementos añadidos. Haz clic en \"Añadir Suplemento\" para empezar.",
        enableAllNotificationsLabel: "Todas las Notificaciones",
        enableAllNotificationsAria: "Activar/desactivar todas las notificaciones de suplementos",
        enableNotificationAria: "Habilitar notificación para {name}",
        disableNotificationAria: "Deshabilitar notificación para {name}",
    }
  },
  fr: { 
    nav: {
      home: 'Accueil',
      exercises: 'Exercices',
      workoutPlans: 'Programmes',
      calendar: 'Calendrier',
      progress: 'Progrès',
      diet: 'Diète',
    },
    userDropdown: {
        myAccount: 'Mon Compte',
        settings: 'Paramètres',
        logout: 'Déconnexion',
    },
    header: {
        toggleTheme: 'Changer de thème',
        openMenu: 'Ouvrir le menu',
    },
     dashboard: {
      welcomeTitle: 'Bienvenue sur SickFit Pro !',
      welcomeDescription: "Votre parcours vers une forme optimale commence ici. Mettons-nous au travail.",
      workoutsThisWeek: 'Entraînements Cette Semaine',
      weightLifted: 'Poids Total Soulevé',
      currentWeight: 'Poids Actuel',
      logNewWorkout: 'Commencer l\'Entraînement',
      todaysFocus: "Focus d'Aujourd'hui",
      todaysFocusDescription: "Qu'y a-t-il au programme aujourd'hui ?",
      checkCalendarForWorkout: "Consultez votre calendrier pour l'entraînement d'aujourd'hui !",
      viewCalendarToSeeWorkout: "Votre entraînement programmé apparaîtra ici.",
      viewFullSchedule: 'Voir le Programme Complet',
      activityAndHistoryTitle: "Activité et Historique",
      noWorkoutHistory: "Aucun historique d'entraînement pour le moment. Terminez un entraînement pour le voir ici !",
      viewAllHistoryButton: "Voir Tout l'Historique",
      todayIsRestDay: "Aujourd'hui, c'est jour de repos ! Profitez-en ! 😊",
      noWorkoutScheduledForToday: "Aucun entraînement programmé pour aujourd'hui.",
    },
    settingsPage: {
      title: 'Paramètres',
      language: 'Langue',
      selectLanguage: 'Sélectionner la langue',
      english: 'Anglais (US)',
      italian: 'Italien',
      spanish: 'Espagnol',
      french: 'Français',
      notifications: 'Notifications',
      allNotificationsLabel: 'Activer Toutes les Notifications de l\'App',
      saveChanges: 'Enregistrer les Modifications',
      settingsSaved: 'Paramètres Enregistrés',
      preferencesUpdated: 'Vos préférences ont été mises à jour',
      profileInformationTitle: 'Informations du Profil',
      uploadProfilePictureLabel: 'Photo de Profil',
      profilePictureAlt: 'Photo de Profil',
      photoSizeError: 'La taille de la photo ne doit pas dépasser 2 Mo.',
      photoSizeLimit: 'Max 2Mo. Format carré recommandé.',
      nameLabel: 'Nom',
      namePlaceholder: 'Entrez votre nom',
      emailLabel: 'E-mail',
      emailCannotBeChanged: 'L\'e-mail ne peut pas être modifié ici.',
      accountSecurityTitle: 'Sécurité du Compte',
      currentPasswordLabel: 'Mot de Passe Actuel',
      newPasswordLabel: 'Nouveau Mot de Passe',
      newPasswordPlaceholder: 'Entrez un nouveau mot de passe (min. 8 caractères)',
      confirmNewPasswordLabel: 'Confirmer le Nouveau Mot de Passe',
      confirmNewPasswordPlaceholder: 'Confirmez le nouveau mot de passe',
      passwordMismatchError: 'Les nouveaux mots de passe ne correspondent pas.',
      passwordChangedTitle: 'Mot de Passe Modifié',
      passwordChangedSuccess: 'Votre mot de passe a été mis à jour avec succès.',
      currentPasswordRequiredError: 'Le mot de passe actuel est requis pour en définir un nouveau.',
      noChangesMadeTitle: 'Aucun Changement',
      noChangesMadeDescription: 'Aucun paramètre n\'a été modifié.',
      toastErrorTitle: 'Erreur',
      showPassword: 'Afficher le mot de passe',
      hidePassword: 'Masquer le mot de passe',
      currentWeightLabel: 'Poids Actuel (kg)',
      currentWeightPlaceholder: 'ex: 70.5',
    },
    toastErrorTitle: "Erreur",
    waterIntakeCard: {
      title: "Apport en Eau",
      currentIntakeLabel: "Actuel: {current}ml / {dailyGoal}ml",
      setDailyGoalLabel: "Objectif Quotidien (ml)",
      saveGoalButton: "Sauvegarder",
      reminderLabel: "Rappel d'Hydratation",
      selectReminderFrequencyPlaceholder: "Fréquence",
      reminderOff: "Désactivé",
      reminderDaily: "Quotidien",
      reminderHourly: "Toutes les heures",
      goalSavedTitle: "Objectif Sauvegardé",
      goalSavedDescription: "Votre objectif quotidien d'apport en eau a été mis à jour.",
      errorInvalidGoal: "Veuillez entrer un objectif valide.",
      resetWaterButton: "Réinitialiser l'Eau",
      waterResetTitle: "Eau Réinitialisée",
      waterResetDescription: "Votre apport en eau pour la journée a été réinitialisé.",
      goalSettingsButtonLabel: "Définir l'Objectif Quotidien",
      goalSettingsAriaLabel: "Paramètres de l'Objectif d'Eau",
      goalSettingsTooltip: "Définissez votre objectif quotidien d'apport en eau",
      ariaAddGlass: "Ajouter un verre ({amount}ml)",
      ariaAddBottle: "Ajouter une bouteille ({amount}ml)",
      tooltipAddAmount: "+{amount}ml",
      hydrationReminderSettingsAriaLabel: "Paramètres du Rappel d'Hydratation",
      hydrationReminderTooltip: "Définir le rappel d'hydratation",
    },
    macroTrackingCard: {
        title: "Suivi des Macros",
        proteinLabel: "Protéines",
        carbsLabel: "Glucides",
        fatLabel: "Lipides",
        setYourWeeklyGoals: "Définissez Vos Objectifs Hebdomadaires de Macros",
        selectDay: "Sélectionner Jour",
        saveGoalsButton: "Sauvegarder Objectifs du Jour",
        monthlyTotalsTitle: "Totaux Mensuels Estimés",
        totalProteinMonth: "Protéines Totales (Mois)",
        totalCarbsMonth: "Glucides Totals (Mois)",
        totalFatMonth: "Lipides Totals (Mois)",
        unitGrams: "g",
        loadingTotals: "Calcul des totaux mensuels...",
        goalsSavedTitle: "Objectifs Macros Sauvegardés",
        goalsForDaySaved: "Objectifs pour {dayOfWeek} sauvegardés avec succès !",
        macroTrendChartTitle: "Tendances des Objectifs de Macronutriments",
        dailyTab: "Quotidien",
        weeklyTab: "Hebdomadaire",
        monthlyTab: "Mensuel",
        weekLabel: "Sem. {weekNum}",
        macroReminderSettingsAriaLabel: "Paramètres de rappel des macros",
        macroReminderTooltip: "Définir le rappel de suivi des macros",
        goalSettingsButtonAriaLabel: "Paramètres des Objectifs Macros",
        goalSettingsTooltip: "Définir les objectifs macros hebdomadaires",
    },
     aiHealthAdvisor: {
        cardTitle: "Conseiller Santé IA",
        dataUsageInfo: "Vos objectifs macro, votre objectif d'apport en eau, vos mesures corporelles et votre résumé d'entraînement stockés seront automatiquement utilisés par l'IA pour fournir des conseils plus personnalisés. Vous pouvez également poser une question spécifique ci-dessous.",
        userQueryLabel: "Votre Question Spécifique (Optionnel)",
        userQueryPlaceholder: "Ex: Comment puis-je améliorer mon sommeil ? ou Quels sont les bons exercices pour le mal de dos ?",
        userQueryDescription: "Posez une question spécifique ou laissez vide pour des conseils généraux basés sur vos données.",
        userQueryMinError: "Si vous posez une question, veuillez fournir au moins 10 caractères.",
        getAdviceButton: "Obtenir Conseil Santé IA",
        adviceReadyTitle: "Conseil Santé Prêt !",
        adviceReadyDescription: "L'IA a généré des conseils de santé pour vous.",
        errorTitle: "Erreur Conseiller",
        errorDescription: "Échec de l'obtention du conseil santé IA. Veuillez réessayer.",
        resultsTitle: "Résultats Conseiller Santé IA",
        overallAssessment: "Évaluation Globale",
        specificAdvice: "Conseils Spécifiques",
    },
    dietPage: {
        title: "Suivi de l'Alimentation",
        description: "Gérez votre apport nutritionnel quotidien et votre hydratation.",
    },
    aiSplitForm: {
        cardTitle: "Conseiller Fitness IA",
        generateAdviceButton: "Générer Conseil",
        generatingSplitTitle: "Génération de vos conseils...",
        generatingSplitDescription: "Notre IA réfléchit. Cela peut prendre un moment.",
        yourSuggestedAdviceTitle: "Votre Conseil Fitness IA",
        suggestedKeyPointsLabel: "Suggestions Clés :",
        detailedAnalysisLabel: "Analyse Détaillée et Conseils :",
        toastSuggestionReadyTitle: "Conseil Prêt !",
        toastSuggestionReadyDescription: "L'IA a généré des conseils d'entraînement pour vous.",
        toastErrorTitle: "Erreur",
        toastErrorDescription: "Échec de l'obtention du conseil IA. Veuillez réessayer.",
        errorFetchingHistory: "Impossible de récupérer automatiquement votre historique d'entraînement. Assurez-vous d'avoir des entraînements enregistrés.",
        noHistoryForAdvice: "Aucun historique d'entraînement disponible pour générer des conseils.",
        genericGoalForAdvice: "Amélioration générale basée sur l'historique des entraînements et les données de progression.",
        promptGenerateAdvice: "Cliquez sur le bouton ci-dessus pour générer des conseils d'entraînement personnalisés basés sur vos données de progression."
    },
    calendarPage: {
        title: "Calendrier d'Entraînement",
        description: "Planifiez et suivez votre programme d'entraînement hebdomadaire.",
        weeklyScheduleTitle: "Programme d'Entraînement Hebdomadaire",
        weeklyScheduleDescription: "Configurez votre semaine d'entraînement type. Ce programme se répétera automatiquement.",
        days: {
          monday: "Lundi",
          tuesday: "Mardi",
          wednesday: "Mercredi",
          thursday: "Jeudi",
          friday: "Vendredi",
          saturday: "Samedi",
          sunday: "Dimanche",
        },
        noWorkoutsForDayOfWeek: "Aucun entraînement programmé pour {dayOfWeek}.",
        addWorkoutToDay: "Ajouter Entraînement",
        cancelButton: "Annuler",
        scheduleWorkoutButton: "Programmer",
        workoutPlanLabel: "Programme d'Entraînement",
        selectAPlanPlaceholder: "Sélectionnez un programme",
        dialogAddWorkoutTitle: "Ajouter Entraînement à {dayOfWeek}",
        dialogAddWorkoutDescription: "Sélectionnez un programme d'entraînement à planifier pour ce jour de la semaine.",
        toastWorkoutScheduledTitle: "Entraînement Programmé !",
        toastWorkoutScheduledDescriptionNoTime: "{planName} le {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Entraînement Supprimé",
        errorSelectDayAndPlan: "Veuillez sélectionner un jour et un programme d'entraînement.",
        errorPlanNotFound: "Programme sélectionné non trouvé.",
        samplePlan1: "Explosion Corps Complet",
        samplePlan2: "Puissance Haut du Corps",
        samplePlan3: "Domination Jour des Jambes",
        samplePlan4: "Séance Cardio",
        loadingCalendar: "Chargement du calendrier...",
    },
    exercisesPage: {
        title: "Exercices Personnalisés",
        description: "Gérez votre bibliothèque d'exercices personnalisés.",
        addNewExerciseButton: "Ajouter un Nouvel Exercice",
        yourExercisesCardTitle: "Vos Exercices",
        tableHeaderName: "Nom",
        tableHeaderMuscleGroup: "Groupe Musculaire",
        tableHeaderType: "Type",
        tableHeaderActions: "Actions",
        dialogAddTitle: "Ajouter un Nouvel Exercice",
        dialogAddDescription: "Remplissez les détails de votre nouvel exercice.",
        dialogEditTitle: "Modifier l'Exercice",
        dialogEditDescription: "Mettez à jour les détails de votre exercice.",
        formNameLabel: "Nom",
        formDescriptionLabel: "Description",
        formMuscleGroupLabel: "Groupe Musculaire",
        selectMuscleGroupPlaceholder: "Sélectionnez un groupe musculaire",
        muscleGroupChest: "Pectoraux",
        muscleGroupBack: "Dos",
        muscleGroupLegs: "Jambes",
        muscleGroupShoulders: "Épaules",
        muscleGroupBiceps: "Biceps",
        muscleGroupTriceps: "Triceps",
        muscleGroupAbs: "Abdominaux",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Autre",
        formTypeLabel: "Type",
        selectExerciseTypePlaceholder: "Sélectionnez un type d'exercice",
        typeStrength: "Force",
        typeCardio: "Cardio",
        typeFlexibility: "Flexibilité",
        typePlyometrics: "Pliométrie",
        typeOther: "Autre",
        cancelButton: "Annuler",
        saveExerciseButton: "Enregistrer l'Exercice",
    },
    progressPage: {
        title: "Suivi des Progrès",
        description: "Visualisez votre parcours de fitness et célébrez vos accomplissements.",
        performanceMetricsCardTitle: "Métrique de Performance",
        bodyCompositionCardTitle: "Composition Corporelle",
        weightLabel: "Poids (kg)",
        photoComparisonCardTitle: "Comparaison de Photos",
        beforePhotoLabel: "Photo Avant",
        afterPhotoLabel: "Photo Après",
        noPhotoUploaded: "Aucune photo téléchargée",
        clickToUpload: "Cliquez pour télécharger",
        uploadButtonLabel: "Télécharger",
        bodyMeasurementsCardTitle: "Mesures Corporelles",
        addMeasurementButton: "Ajouter Mesure",
        measurementDialogAddTitle: "Ajouter Nouvelle Mesure",
        measurementDialogEditTitle: "Modifier Mesure",
        measurementDialogDescription: "Entrez les détails de votre mesure.",
        formDateLabel: "Date",
        formMeasurementNameLabel: "Type de Mesure",
        selectMeasurementNamePlaceholder: "Sélectionnez un type de mesure",
        measurementNameBiceps: "Biceps",
        measurementNameChest: "Pectoraux",
        measurementNameWaist: "Taille",
        measurementNameHips: "Hanches",
        measurementNameThigh: "Cuisse",
        measurementNameCalf: "Mollet",
        measurementNameWeight: "Poids",
        measurementNameHeight: "Taille (hauteur)",
        formValueLabel: "Valeur",
        unitCM: "cm",
        unitIN: "pouces",
        unitKG: "kg",
        unitLBS: "livres",
        formNotesLabel: "Notes",
        formNotesPlaceholder: "Entrez des notes pertinentes...",
        saveMeasurementButton: "Enregistrer Mesure",
        tableHeaderDate: "Date",
        tableHeaderMeasurementName: "Mesure",
        tableHeaderValue: "Valeur",
        measurementReminderLabel: "Rappel de Mesure",
        selectReminderFrequencyPlaceholder: "Sélectionnez la fréquence",
        reminderOff: "Désactivé",
        reminderDaily: "Quotidien",
        reminderWeekly: "Hebdomadaire",
        reminderBiWeekly: "Bihebdomadaire",
        reminderMonthly: "Mensuel",
        measurementSaved: "Mesure Enregistrée",
        measurementDeleted: "Mesure Supprimée",
        noMeasurementsYet: "Aucune mesure enregistrée pour l'instant. Ajoutez votre première !",
        formValidationAlert: "Veuillez remplir la date, le type de mesure et la valeur.",
        timeRangeWeekly: "Hebdo",
        timeRangeMonthly: "Mensuel",
        timeRangeYearly: "Annuel",
        muscleGroupChestChart: "Pectoraux (Volume)",
        muscleGroupBackChart: "Dos (Volume)",
        muscleGroupLegsChart: "Jambes (Volume)",
        muscleGroupShouldersChart: "Épaules (Volume)",
        muscleGroupBicepsChart: "Biceps (Volume)",
        muscleGroupTricepsChart: "Triceps (Volume)",
        weekShortLabel: "S{num}",
        weeklyTrainingVolumeLabel: "Volume d'Entraînement",
    },
    workoutPlansPage: {
        title: "Programmes d'Entraînement",
        description: "Créez, gérez et partagez vos programmes d'entraînement.",
        createNewPlanButton: "Créer un Nouveau Programme",
        estDurationLabel: "Durée Estimée",
        exercisesLabel: "Exercices",
        involvedMusclesLabel: "Muscles Impliqués :",
        startButton: "Commencer",
        dialogEditTitle: "Modifier le Programme d'Entraînement",
        dialogEditDescription: "Mettez à jour les détails de votre programme d'entraînement.",
        dialogCreateTitle: "Créer un Nouveau Programme d'Entraînement",
        dialogCreateDescription: "Concevez votre nouveau programme d'entraînement.",
        planNameLabel: "Nom du Programme",
        descriptionLabel: "Description",
        exerciseNameLabel: "Nom de l'Exercice",
        setsLabel: "Séries",
        repsLabel: "Répétitions",
        addThisExerciseButton: "Ajouter cet Exercice",
        addedExercisesLabel: "Exercices Ajoutés :",
        noExercisesAddedYet: "Aucun exercice ajouté à ce programme pour l'instant.",
        cancelButton: "Annuler",
        savePlanButton: "Enregistrer le Programme",
        toastPlanUpdatedTitle: "Programme Mis à Jour",
        toastPlanUpdatedDescription: '"{planName}" a été mis à jour.',
        toastPlanCreatedTitle: "Programme Créé",
        toastPlanCreatedDescription: '"{planName}" a été créé.',
        toastPlanDeletedTitle: "Programme Supprimé",
        toastPlanDeletedDescription: '"{planName}" a été supprimé.',
        toastLinkCopiedTitle: "Lien Copié !",
        toastLinkCopiedDescription: "Lien du programme d'entraînement copié dans le presse-papiers.",
        muscleSilhouetteAlt: "Groupes musculaires impliqués dans le programme",
        noMuscleGroupsSpecified: "N/A"
    },
    startWorkoutPage: {
      title: "Commencer un Nouvel Entraînement",
      description: "Choisissez un programme pour commencer ou lancez une session ad-hoc.",
      selectPlanTitle: "Sélectionnez un Programme",
      noPlansAvailable: "Aucun programme d'entraînement disponible. Créez-en un d'abord !",
      startPlanButton: "Commencer Programme",
    },
    activeWorkoutPage: {
        title: "Entraînement Actif : {planName}",
        description: "Suivez vos séries, répétitions et poids pour cette session.",
        finishWorkoutButton: "Terminer l'Entraînement",
        logSetButton: "Enregistrer Série",
        planNotFound: "Programme d'entraînement non trouvé.",
        planNotFoundDescription: "Veuillez vérifier l'URL ou revenez en arrière pour sélectionner un programme valide.",
        loadingWorkout: "Chargement de l'Entraînement...",
        loadingDescription: "Veuillez patienter pendant que nous chargeons les détails du programme.",
        targetSetsLabel: "Séries Cibles",
        targetRepsLabel: "Répétitions Cibles",
        repsInputLabel: "Répétitions",
        weightInputLabel: "Poids (kg)",
        setColumnLabel: "Série",
        dateColumnLabel: "Date",
        repsColumnLabel: "Répétitions",
        weightColumnLabel: "Poids (kg)",
        toastSetLoggedTitle: "Série Enregistrée",
        toastSetLoggedDescription: "Série pour {exerciseName} enregistrée.",
        toastSetDeletedTitle: "Série Supprimée",
        toastWorkoutFinishedTitle: "Entraînement Terminé !",
        toastWorkoutFinishedDescription: "Excellent travail pour avoir terminé votre entraînement en {duration} !",
        overallProgressLabel: "Progression Globale de l'Entraînement",
        setCompletionLabel: "Séries : {completed}/{total}",
        noGifAvailable: "Aucun GIF disponible",
        exerciseDemoAlt: "démonstration de l'exercice",
        completeWorkoutButton: "Terminer l'Entraînement",
        workoutCompleteTitle: "Entraînement Terminé !",
        workoutCompleteDescription: "Vous avez terminé avec succès l'entraînement {planName}.",
        totalTimeLabel: "Temps Total",
        backToDashboardButton: "Retour à l'Accueil",
        confirmFinishTitle: "Terminer l'Entraînement ?",
        confirmFinishDescription: "Êtes-vous sûr de vouloir marquer cet entraînement comme terminé ?",
        confirmFinishButton: "Oui, Terminer",
        noSetsLoggedYet: "Aucune série enregistrée pour cet exercice.",
        sessionPBsLabel: "RP de Session",
        maxWeightLabel: "Poids Max",
        maxRepsLabel: "Rép. Max",
        repsUnitLabel: "réps",
        workoutInProgressTitle: "Entraînement en Cours",
        finishCurrentWorkoutPrompt: "Vous avez un entraînement actif. Veuillez le terminer ou l'abandonner avant d'en commencer un nouveau ou de créer/modifier des programmes.",
    },
    resumeWorkoutButton: {
      resumeTitle: "Reprendre l'entraînement",
      resume: "Reprendre : {planName}",
    },
    supplements: {
        cardTitle: "Suivi des Suppléments",
        addSupplementButton: "Ajouter un Supplément",
        tableHeaderName: "Nom",
        tableHeaderTiming: "Quand",
        tableHeaderQuantity: "Quantité",
        tableHeaderFrequency: "Fréquence",
        tableHeaderTime: "Heure",
        tableHeaderNotifications: "Notifier",
        dialogEditTitle: "Modifier le Supplément",
        dialogAddTitle: "Ajouter un Nouveau Supplément",
        dialogDescription: "Remplissez les détails de votre supplément.",
        formNameLabel: "Nom",
        formTimingLabel: "Quand prendre (ex. Matin, Post-entraînement)",
        formQuantityLabel: "Quantité (ex. 1 dosette, 2 gélules)",
        formFrequencyLabel: "Fréquence",
        selectFrequencyPlaceholder: "Sélectionnez la fréquence",
        frequencyDaily: "Quotidienne",
        frequencyWeekly: "Hebdomadaire",
        frequencyMonthly: "Mensuelle",
        frequencyCustom: "Personnalisée",
        formTimeLabel: "Heure Spécifique (HH:MM, optionnel)",
        enableNotificationForSupplement: "Activer la notification pour ce supplément",
        toastAddedTitle: "Supplément Ajouté",
        toastUpdatedTitle: "Supplément Mis à Jour",
        toastDeletedTitle: "Supplément Supprimé",
        errorAllFieldsRequired: "Le nom, le moment et la quantité sont requis.",
        noSupplementsAdded: "Aucun supplément ajouté pour le moment. Cliquez sur \"Ajouter un Supplément\" pour commencer.",
        enableAllNotificationsLabel: "Toutes les Notifications",
        enableAllNotificationsAria: "Activer/désactiver toutes les notifications de suppléments",
        enableNotificationAria: "Activer la notification pour {name}",
        disableNotificationAria: "Désactiver la notification pour {name}",
    }
  }
};


interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string | number | undefined>) => string;
  isClient: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(DEFAULT_LANGUAGE);
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    let clientInitialLanguage = DEFAULT_LANGUAGE;
    try {
      const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
      if (storedLanguage && translations[storedLanguage]) {
        clientInitialLanguage = storedLanguage;
      } else {
         localStorage.setItem(LANGUAGE_STORAGE_KEY, DEFAULT_LANGUAGE);
      }
    } catch (e) {
      console.warn('LanguageProvider: Failed to access localStorage. Using default language.', e);
    }

    if (clientInitialLanguage !== language) {
      setLanguageState(clientInitialLanguage);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const setLanguage = useCallback((newLanguage: Language) => {
    if (translations[newLanguage]) {
      try {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage);
      } catch (e) {
         console.warn('LanguageProvider: Failed to save language to localStorage.', e);
      }
      setLanguageState(newLanguage);
      if (typeof document !== 'undefined') {
        document.documentElement.lang = newLanguage;
      }
    } else {
      console.warn(`LanguageProvider: Attempted to set unsupported language "${newLanguage}"`);
    }
  }, []);

  const t = useCallback((key: string, replacements?: Record<string, string | number | undefined>): string => {
    const currentLang = isClient ? language : DEFAULT_LANGUAGE;
    const keys = key.split('.');
    let result: any = translations[currentLang];

    for (const k of keys) {
      result = result?.[k];
      if (result === undefined) {
        let fallbackResult: any = translations[DEFAULT_LANGUAGE];
        for (const fk of keys) {
            fallbackResult = fallbackResult?.[fk];
            if (fallbackResult === undefined) {
              return replacements?.default?.toString() || key;
            }
        }
        result = fallbackResult;
        break;
      }
    }

    if (typeof result === 'string' && replacements) {
      const actualReplacements = { ...replacements };
      delete actualReplacements.default;

      return Object.entries(actualReplacements).reduce((acc, [placeholder, value]) => {
        const replacementValue = (typeof value === 'string' || typeof value === 'number') ? String(value) : '';
        return acc.replace(new RegExp(`{${placeholder}}`, 'g'), replacementValue);
      }, result);
    }
    
    return typeof result === 'string' ? result : (replacements?.default?.toString() || key) ;
  }, [language, isClient]);


  useEffect(() => {
    if (isClient) {
      document.documentElement.lang = language;
    }
  }, [language, isClient]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isClient }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

