
// src/context/language-context.tsx
'use client';

import type { ReactNode } from 'react';
import { createContext, useContext, useEffect, useState, useCallback } from 'react';

export type Language = 'en' | 'it' | 'es' | 'fr';
const DEFAULT_LANGUAGE: Language = 'en';
const LANGUAGE_STORAGE_KEY = 'app-language';

interface Translations {
  [key: string]: string | Translations;
}

const translations: Record<Language, Translations> = {
  en: {
    nav: {
      dashboard: 'Home',
      exercises: 'Exercises',
      workoutPlans: 'Workout Plans',
      calendar: 'Calendar',
      progress: 'Progress',
      diet: 'Diet',
    },
    userDropdown: {
      myAccount: 'My Account',
      settings: 'Settings',
      theme: 'Theme',
      light: 'Light',
      dark: 'Dark',
      system: 'System',
      logout: 'Log out',
    },
    header: {
      toggleTheme: 'Toggle theme',
    },
    dashboard: {
      welcomeTitle: 'Welcome to SickFit Pro!',
      welcomeDescription: "Your journey to peak fitness starts here. Let's get to work.",
      workoutsThisWeek: 'Workouts This Week',
      weightLifted: 'Total Weight Lifted',
      currentWeight: 'Current Weight',
      logNewWorkout: 'Start Workout',
      todaysFocus: "Today's Focus",
      todaysFocusDescription: "What's on the agenda for today?",
      checkCalendarForWorkout: "Check your calendar for today's workout!",
      viewCalendarToSeeWorkout: "Your scheduled workout will appear here.",
      viewFullSchedule: 'View Full Schedule',
      activityAndHistoryTitle: "Activity & History",
      activityAndHistoryDescription: "Start a new workout or review your past sessions.",
      noWorkoutHistory: "No workout history yet. Complete a workout to see it here!",
      viewAllHistoryButton: "View All History",
      todayIsRestDay: "Today is a rest day! Enjoy it! 😊",
      noWorkoutScheduledForToday: "No workout scheduled for today.",
    },
    waterIntakeCard: {
      title: "Water Intake",
      description: "Stay hydrated! Your goal: {dailyGoal} ml.",
      currentIntakeLabel: "Current: {current}ml / {dailyGoal}ml",
      setGoalLabel: "Set Daily Goal (ml)",
      saveGoalButton: "Save Goal",
      goalSavedTitle: "Goal Saved",
      goalSavedDescription: "Your daily water intake goal has been updated.",
      resetWaterButton: "Reset Water",
      waterResetTitle: "Water Reset",
      waterResetDescription: "Your water intake for the day has been reset.",
      ariaAddGlass: "Add glass ({amount}ml)",
      ariaAddBottle: "Add bottle ({amount}ml)",
      ariaRemoveGenericAmount: "Remove {amount}ml",
      tooltipAddAmount: "+{amount}ml",
      tooltipRemoveAmount: "-{amount}ml",
      reminderLabel: "Hydration Reminder",
      selectReminderFrequencyPlaceholder: "Set reminder frequency",
      reminderOff: "Off",
      reminderDaily: "Daily",
      reminderHourly: "Hourly",
    },
    macroTrackingCard: {
        title: "Macro Tracking",
        description: "Monitor your daily protein, carbs, and fat intake.",
        descriptionWeekly: "Plan your weekly macronutrient targets and see monthly estimates.",
        proteinLabel: "Protein",
        carbsLabel: "Carbs",
        fatLabel: "Fat",
        goalLabel: "Goal (g)",
        currentLabel: "Current (g)",
        setYourDailyGoals: "Set Your Daily Goals",
        setYourWeeklyGoals: "Set Your Weekly Macro Goals",
        selectDay: "Select Day",
        logYourDailyIntake: "Log Your Daily Intake",
        saveGoalsButton: "Save Goals for Day",
        saveIntakeButton: "Save Intake",
        goalsSavedTitle: "Macro Goals Saved",
        goalsSavedDescription: "Your daily macronutrient goals have been updated.",
        goalsForDaySaved: "Goals for {dayOfWeek} saved successfully!",
        intakeSavedTitle: "Macro Intake Saved",
        intakeSavedDescription: "Your daily macronutrient intake has been recorded.",
        reminderLabel: "Macro Logging Reminder",
        selectReminderFrequencyPlaceholder: "Set reminder frequency",
        reminderOff: "Off",
        reminderDaily: "Daily",
        reminderMealtime: "Around Mealtimes",
        monthlyTotalsTitle: "Estimated Monthly Totals",
        totalProteinMonth: "Total Protein (Month)",
        totalCarbsMonth: "Total Carbs (Month)",
        totalFatMonth: "Total Fat (Month)",
        unitGrams: "g",
        loadingTotals: "Calculating monthly totals...",
    },
    nutritionalAnalysis: {
        cardTitle: "Nutritional Analysis (AI)",
        cardDescription: "Describe your meal or upload a photo to get an AI-powered nutritional breakdown and advice.",
        mealDescriptionLabel: "Meal Description",
        mealDescriptionPlaceholder: "e.g., Grilled chicken breast with quinoa and steamed broccoli.",
        mealPhotoLabel: "Meal Photo (Optional)",
        uploadPhotoButton: "Upload Photo",
        photoPreviewAlt: "Meal photo preview",
        removePhoto: "Remove Photo",
        analyzeMealButton: "Analyze Meal",
        analyzingTitle: "Analyzing Meal...",
        analyzingDescription: "Our AI is looking at your meal. This might take a moment.",
        analysisReadyTitle: "Analysis Ready!",
        analysisReadyDescription: "Nutritional analysis for your meal is complete.",
        errorTitle: "Analysis Error",
        errorDescription: "Could not analyze the meal. Please try again.",
        resultsTitle: "Nutritional Analysis Results",
        estimatedCalories: "Estimated Calories",
        protein: "Protein (g)",
        carbs: "Carbs (g)",
        fat: "Fat (g)",
        generalAdvice: "General Advice",
        noPhotoSelected: "No photo selected",
    },
    settingsPage: {
      title: 'Settings',
      language: 'Language',
      selectLanguage: 'Select language',
      english: 'English (US)',
      italian: 'Italiano (Italian)',
      spanish: 'Español (Spanish)',
      french: 'Français (French)',
      notifications: 'Notifications',
      allNotificationsLabel: 'Enable All App Notifications',
      saveChanges: 'Save Changes',
      settingsSaved: 'Settings Saved',
      preferencesUpdated: 'Your preferences have been updated',
      profileInformationTitle: 'Profile Information',
      uploadProfilePictureLabel: 'Profile Picture',
      profilePictureAlt: 'Profile Picture',
      photoSizeError: 'Photo size should not exceed 2MB.',
      photoSizeLimit: 'Max 2MB. Recommended square aspect ratio.',
      nameLabel: 'Name',
      namePlaceholder: 'Enter your name',
      emailLabel: 'Email',
      emailCannotBeChanged: 'Email cannot be changed here.',
      accountSecurityTitle: 'Account Security',
      currentPasswordLabel: 'Current Password',
      newPasswordLabel: 'New Password',
      newPasswordPlaceholder: 'Enter new password (min. 8 characters)',
      confirmNewPasswordLabel: 'Confirm New Password',
      confirmNewPasswordPlaceholder: 'Confirm new password',
      passwordMismatchError: 'New passwords do not match.',
      passwordChangedTitle: 'Password Changed',
      passwordChangedSuccess: 'Your password has been updated successfully.',
      currentPasswordRequiredError: 'Current password is required to set a new one.',
      noChangesMadeTitle: 'No Changes',
      noChangesMadeDescription: 'No settings were modified.',
      toastErrorTitle: 'Error',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      currentWeightLabel: 'Current Weight (kg)',
      currentWeightPlaceholder: 'e.g., 70.5',
    },
    aiSplitForm: {
        cardTitle: "AI Fitness Advisor",
        cardDescription: "Get personalized training advice from our AI coach. Your recent training history will be automatically analyzed along with your goals.",
        trainingHistoryAutoCollectedInfo: "Your recent training history is automatically collected to provide personalized advice.",
        trainingGoalsLabel: "Training Goals",
        trainingGoalsPlaceholder: "e.g., Looking to gain muscle mass, improve strength in compound lifts, and increase overall endurance. Specifically want to grow my legs and shoulders.",
        trainingGoalsDescription: "What do you want to achieve with your training? (e.g., muscle gain, fat loss, strength increase)",
        trainingGoalsMinError: "Please describe your training goals (at least 10 characters).",
        getAISuggestionButton: "Get AI Advice",
        generatingSplitTitle: "Generating your advice...",
        generatingSplitDescription: "Our AI is thinking. This might take a moment.",
        yourSuggestedAdviceTitle: "Your AI Fitness Advice",
        suggestedKeyPointsLabel: "Key Suggestions:",
        detailedAnalysisLabel: "Detailed Analysis & Advice:",
        toastSuggestionReadyTitle: "Advice Ready!",
        toastSuggestionReadyDescription: "AI has generated training advice for you.",
        toastErrorTitle: "Error",
        toastErrorDescription: "Failed to get AI advice. Please try again.",
        errorFetchingHistory: "Could not automatically retrieve your training history. Please ensure you have some logged workouts.",
    },
    calendarPage: {
        title: "Workout Calendar",
        description: "Plan and track your weekly training schedule.",
        selectADate: "Select a Date",
        workoutsScheduledForThisDay: "Workouts scheduled for this day.",
        addWorkoutToDay: "Add Workout",
        noWorkoutsScheduled: "No workouts scheduled for this day.",
        selectDateToSeeWorkouts: "Select a date to see scheduled workouts.",
        dialogAddWorkoutTitle: "Add Workout to {dayOfWeek}",
        dialogAddWorkoutDescription: "Select a workout plan to schedule for this day of the week.",
        workoutPlanLabel: "Workout Plan",
        selectAPlanPlaceholder: "Select a plan",
        samplePlan1: "Full Body Blast",
        samplePlan2: "Upper Body Power",
        samplePlan3: "Leg Day Domination",
        samplePlan4: "Cardio Session",
        cancelButton: "Cancel",
        scheduleWorkoutButton: "Schedule Workout",
        loadingCalendar: "Loading calendar...",
        weeklyScheduleTitle: "Weekly Training Schedule",
        weeklyScheduleDescription: "Set up your typical training week. This schedule will repeat automatically.",
        days: {
          monday: "Monday",
          tuesday: "Tuesday",
          wednesday: "Wednesday",
          thursday: "Thursday",
          friday: "Friday",
          saturday: "Saturday",
          sunday: "Sunday",
        },
        noWorkoutsForDayOfWeek: "No workouts scheduled for {dayOfWeek}.",
        addWorkoutTo: "Add to {dayOfWeek}",
        toastWorkoutScheduledTitle: "Workout Scheduled!",
        toastWorkoutScheduledDescriptionNoTime: "{planName} on {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Workout Removed",
        errorSelectDayAndPlan: "Please select a day and a workout plan.",
        errorPlanNotFound: "Selected plan not found.",
    },
    exercisesPage: {
        title: "Custom Exercises",
        description: "Manage your personalized exercise library.",
        addNewExerciseButton: "Add New Exercise",
        yourExercisesCardTitle: "Your Exercises",
        tableHeaderName: "Name",
        tableHeaderMuscleGroup: "Muscle Group",
        tableHeaderType: "Type",
        tableHeaderActions: "Actions",
        dialogAddTitle: "Add New Exercise",
        dialogAddDescription: "Fill in the details for your new exercise.",
        dialogEditTitle: "Edit Exercise",
        dialogEditDescription: "Update the details of your exercise.",
        formNameLabel: "Name",
        formDescriptionLabel: "Description",
        formMuscleGroupLabel: "Muscle Group",
        selectMuscleGroupPlaceholder: "Select muscle group",
        muscleGroupChest: "Chest",
        muscleGroupBack: "Back",
        muscleGroupLegs: "Legs",
        muscleGroupShoulders: "Shoulders",
        muscleGroupBiceps: "Biceps",
        muscleGroupTriceps: "Triceps",
        muscleGroupAbs: "Abs",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Other",
        formTypeLabel: "Type",
        selectExerciseTypePlaceholder: "Select exercise type",
        typeStrength: "Strength",
        typeCardio: "Cardio",
        typeFlexibility: "Flexibility",
        typePlyometrics: "Plyometrics",
        typeOther: "Other",
        cancelButton: "Cancel",
        saveExerciseButton: "Save Exercise",
    },
    progressPage: {
        title: "Progress Tracking",
        description: "Visualize your fitness journey and celebrate your achievements.",
        performanceMetricsCardTitle: "Performance Metrics",
        performanceMetricsCardDescription: "Track your key lifts and measurements over time.",
        weeklyTrainingVolumeLabel: "Weekly Training Volume (kg)",
        benchPressLabel: "Bench Press (kg)",
        squatLabel: "Squat (kg)",
        bodyCompositionCardTitle: "Body Composition",
        bodyCompositionCardDescription: "Monitor changes in weight, body fat, etc.",
        weightLabel: "Weight (kg)",
        photoComparisonCardTitle: "Photo Comparison",
        photoComparisonCardDescription: "Visually track your transformation. Upload 'before' and 'after' photos.",
        beforePhotoLabel: "Before Photo",
        afterPhotoLabel: "After Photo",
        noPhotoUploaded: "No photo uploaded",
        clickToUpload: "Click to upload",
        uploadButtonLabel: "Upload",
        bodyMeasurementsCardTitle: "Body Measurements",
        bodyMeasurementsCardDescription: "Track your body measurements like weight, height, and muscle size over time.",
        addMeasurementButton: "Add Measurement",
        measurementDialogAddTitle: "Add New Measurement",
        measurementDialogEditTitle: "Edit Measurement",
        measurementDialogDescription: "Enter the details for your measurement.",
        formDateLabel: "Date",
        formMeasurementNameLabel: "Measurement Type",
        selectMeasurementNamePlaceholder: "Select measurement type",
        measurementNameBiceps: "Biceps",
        measurementNameChest: "Chest",
        measurementNameWaist: "Waist",
        measurementNameHips: "Hips",
        measurementNameThigh: "Thigh",
        measurementNameCalf: "Calf",
        measurementNameWeight: "Weight",
        measurementNameHeight: "Height",
        formValueLabel: "Value",
        formUnitLabel: "Unit",
        unitCM: "cm",
        unitIN: "in",
        unitKG: "kg",
        unitLBS: "lbs",
        formNotesLabel: "Notes",
        formNotesPlaceholder: "Enter any relevant notes...",
        saveMeasurementButton: "Save Measurement",
        tableHeaderDate: "Date",
        tableHeaderMeasurementName: "Measurement",
        tableHeaderValue: "Value",
        measurementReminderLabel: "Measurement Reminder",
        selectReminderFrequencyPlaceholder: "Set reminder frequency",
        reminderOff: "Off",
        reminderDaily: "Daily",
        reminderWeekly: "Weekly",
        reminderBiWeekly: "Bi-Weekly",
        reminderMonthly: "Monthly",
        measurementSaved: "Measurement Saved",
        measurementDeleted: "Measurement Deleted",
        noMeasurementsYet: "No measurements recorded yet. Add your first one!",
        formValidationAlert: "Please fill in date, measurement type, and value.",
    },
    workoutPlansPage: {
        title: "Workout Plans",
        description: "Create, manage, and share your training schedules.",
        createNewPlanButton: "Create New Plan",
        exercisesLabel: "Exercises",
        estDurationLabel: "Est. Duration",
        startButton: "Start",
        dialogEditTitle: "Edit Workout Plan",
        dialogEditDescription: "Update the details of your workout plan.",
        dialogCreateTitle: "Create New Workout Plan",
        dialogCreateDescription: "Design your new workout plan.",
        planNameLabel: "Plan Name",
        descriptionLabel: "Description",
        exerciseNameLabel: "Exercise Name",
        setsLabel: "Sets",
        repsLabel: "Reps",
        addThisExerciseButton: "Add this Exercise",
        addedExercisesLabel: "Added Exercises:",
        noExercisesAddedYet: "No exercises added to this plan yet.",
        exerciseSelectionPlaceholder: "Add exercises to this plan using the form above.",
        addExerciseButton: "Add Exercise to Plan",
        cancelButton: "Cancel",
        savePlanButton: "Save Plan",
        toastPlanUpdatedTitle: "Plan Updated",
        toastPlanUpdatedDescription: "\"{planName}\" has been updated.",
        toastPlanCreatedTitle: "Plan Created",
        toastPlanCreatedDescription: "\"{planName}\" has been created.",
        toastPlanDeletedTitle: "Plan Deleted",
        toastPlanDeletedDescription: "\"{planName}\" has been deleted.",
        toastLinkCopiedTitle: "Link Copied!",
        toastLinkCopiedDescription: "Workout plan link copied to clipboard.",
        muscleSilhouetteAlt: "Muscle groups involved in the plan",
        muscleGroupsLabel: "Muscle Groups",
    },
     startWorkoutPage: {
      title: "Start New Workout",
      description: "Choose a plan to start or begin an ad-hoc session.",
      selectPlanTitle: "Select a Plan",
      startAdHocButton: "Start Ad-hoc Workout",
      noPlansAvailable: "No workout plans available. Create one first!",
      startPlanButton: "Start Plan",
    },
    activeWorkoutPage: {
      title: "Active Workout: {planName}",
      description: "Track your sets, reps, and weights for this session.",
      finishWorkoutButton: "Finish Workout",
      logSetButton: "Log Set",
      planNotFound: "Workout plan not found.",
      planNotFoundDescription: "Please check the URL or go back to select a valid plan.",
      loadingWorkout: "Loading Workout...",
      loadingDescription: "Please wait while we fetch the plan details.",
      targetSetsLabel: "Target Sets",
      targetRepsLabel: "Target Reps",
      repsInputLabel: "Reps",
      weightInputLabel: "Weight (kg)",
      setColumnLabel: "Set",
      dateColumnLabel: "Date",
      repsColumnLabel: "Reps",
      weightColumnLabel: "Weight (kg)",
      toastSetLoggedTitle: "Set Logged",
      toastSetLoggedDescription: "Set for {exerciseName} recorded.",
      toastSetDeletedTitle: "Set Deleted",
      toastWorkoutFinishedTitle: "Workout Finished!",
      toastWorkoutFinishedDescription: "Great job completing your workout in {duration}!",
      overallProgressLabel: "Overall Workout Progress",
      setCompletionLabel: "Sets: {completed}/{total}",
      noGifAvailable: "No GIF available",
      exerciseDemoAlt: "exercise demonstration",
      nextExerciseButton: "Next Exercise",
      completeWorkoutButton: "Complete Workout",
      workoutCompleteTitle: "Workout Complete!",
      workoutCompleteDescription: "You've successfully completed the {planName} workout.",
      totalTimeLabel: "Total Time",
      backToDashboardButton: "Back to Home",
      confirmFinishTitle: "Finish Workout?",
      confirmFinishDescription: "Are you sure you want to mark this workout as complete?",
      confirmFinishButton: "Yes, Finish",
      noSetsLoggedYet: "No sets logged for this exercise yet.",
      sessionPBsLabel: "Session PBs",
      maxWeightLabel: "Max Weight",
      maxRepsLabel: "Max Reps",
      repsUnitLabel: "reps",
      workoutInProgressTitle: "Workout In Progress",
      finishCurrentWorkoutPrompt: "You have an active workout. Please finish or abandon it before starting a new one or creating/editing plans.",
    },
    dietPage: {
        title: "Diet Tracking",
        description: "Manage your daily nutritional intake and hydration.",
    },
    toastErrorTitle: "Error",
    resumeWorkoutButton: {
      resumeTitle: "Resume Workout",
      resume: "Resume: {planName}",
    }
  },
  it: {
    nav: {
      dashboard: 'Home', 
      exercises: 'Esercizi',
      workoutPlans: 'Schede', 
      calendar: 'Calendario',
      progress: 'Progressi',
      diet: 'Dieta',
    },
    userDropdown: {
      myAccount: 'Il Mio Account',
      settings: 'Impostazioni',
      theme: 'Tema',
      light: 'Chiaro',
      dark: 'Scuro',
      system: 'Sistema',
      logout: 'Esci',
    },
    header: {
      toggleTheme: 'Cambia tema',
    },
    dashboard: {
      welcomeTitle: 'Benvenuto in SickFit Pro!',
      welcomeDescription: 'Il tuo viaggio verso la forma fisica ottimale inizia qui. Mettiamoci al lavoro.',
      workoutsThisWeek: 'Allenamenti Settimanali',
      weightLifted: 'Peso Totale Sollevato',
      currentWeight: 'Peso Attuale',
      logNewWorkout: 'Inizia Allenamento',
      todaysFocus: "Focus di Oggi",
      todaysFocusDescription: "Cosa c'è in programma per oggi?",
      checkCalendarForWorkout: "Controlla il calendario per l'allenamento di oggi!",
      viewCalendarToSeeWorkout: "Il tuo allenamento programmato apparirà qui.",
      viewFullSchedule: 'Visualizza Programma Completo',
      activityAndHistoryTitle: "Attività e Cronologia",
      activityAndHistoryDescription: "Inizia un nuovo allenamento o rivedi le tue sessioni passate.",
      noWorkoutHistory: "Nessuno storico allenamenti ancora. Completa un allenamento per vederlo qui!",
      viewAllHistoryButton: "Visualizza Tutto lo Storico",
      todayIsRestDay: "Oggi è giorno di riposo! Goditelo! 😊",
      noWorkoutScheduledForToday: "Nessun allenamento programmato per oggi.",
    },
    waterIntakeCard: {
      title: "Apporto Idrico",
      description: "Rimani idratato! Il tuo obiettivo giornaliero: {dailyGoal} ml.",
      currentIntakeLabel: "Attuale: {current}ml / {dailyGoal}ml",
      setGoalLabel: "Imposta Obiettivo Giornaliero (ml)",
      saveGoalButton: "Salva Obiettivo",
      goalSavedTitle: "Obiettivo Salvato",
      goalSavedDescription: "Il tuo obiettivo di apporto idrico giornaliero è stato aggiornato.",
      resetWaterButton: "Resetta Acqua",
      waterResetTitle: "Apporto Idrico Azzerato",
      waterResetDescription: "Il tuo apporto idrico giornaliero è stato azzerato.",
      ariaAddGlass: "Aggiungi bicchiere ({amount}ml)",
      ariaAddBottle: "Aggiungi bottiglia ({amount}ml)",
      ariaRemoveGenericAmount: "Rimuovi {amount}ml",
      tooltipAddAmount: "+{amount}ml",
      tooltipRemoveAmount: "-{amount}ml",
      reminderLabel: "Promemoria Idratazione",
      selectReminderFrequencyPlaceholder: "Imposta frequenza promemoria",
      reminderOff: "Spento",
      reminderDaily: "Giornaliero",
      reminderHourly: "Ogni ora",
    },
    macroTrackingCard: {
        title: "Monitoraggio Macro",
        description: "Monitora il tuo apporto giornaliero di proteine, carboidrati e grassi.",
        descriptionWeekly: "Pianifica i tuoi obiettivi di macronutrienti settimanali e visualizza le stime mensili.",
        proteinLabel: "Proteine",
        carbsLabel: "Carboidrati",
        fatLabel: "Grassi",
        goalLabel: "Obiettivo (g)",
        currentLabel: "Attuale (g)",
        setYourDailyGoals: "Imposta i Tuoi Obiettivi Giornalieri",
        setYourWeeklyGoals: "Imposta i Tuoi Obiettivi Macro Settimanali",
        selectDay: "Seleziona Giorno",
        logYourDailyIntake: "Registra il Tuo Apporto Giornaliero",
        saveGoalsButton: "Salva Obiettivi del Giorno",
        saveIntakeButton: "Salva Apporto",
        goalsSavedTitle: "Obiettivi Macro Salvati",
        goalsSavedDescription: "I tuoi obiettivi giornalieri di macronutrienti sono stati aggiornati.",
        goalsForDaySaved: "Obiettivi per {dayOfWeek} salvati con successo!",
        intakeSavedTitle: "Apporto Macro Salvato",
        intakeSavedDescription: "Il tuo apporto giornaliero di macronutrienti è stato registrato.",
        reminderLabel: "Promemoria Log Macro",
        selectReminderFrequencyPlaceholder: "Imposta frequenza promemoria",
        reminderOff: "Spento",
        reminderDaily: "Giornaliero",
        reminderMealtime: "Intorno ai Pasti",
        monthlyTotalsTitle: "Totali Mensili Stimati",
        totalProteinMonth: "Proteine Totali (Mese)",
        totalCarbsMonth: "Carboidrati Totali (Mese)",
        totalFatMonth: "Grassi Totali (Mese)",
        unitGrams: "g",
        loadingTotals: "Calcolo totali mensili...",
    },
    nutritionalAnalysis: {
        cardTitle: "Analisi Nutrizionale (AI)",
        cardDescription: "Descrivi il tuo pasto o carica una foto per ottenere un'analisi nutrizionale e consigli basati sull'AI.",
        mealDescriptionLabel: "Descrizione Pasto",
        mealDescriptionPlaceholder: "es. Petto di pollo alla griglia con quinoa e broccoli al vapore.",
        mealPhotoLabel: "Foto Pasto (Opzionale)",
        uploadPhotoButton: "Carica Foto",
        photoPreviewAlt: "Anteprima foto pasto",
        removePhoto: "Rimuovi Foto",
        analyzeMealButton: "Analizza Pasto",
        analyzingTitle: "Analisi Pasto in Corso...",
        analyzingDescription: "La nostra AI sta analizzando il tuo pasto. Potrebbe volerci un momento.",
        analysisReadyTitle: "Analisi Pronta!",
        analysisReadyDescription: "L'analisi nutrizionale per il tuo pasto è completa.",
        errorTitle: "Errore Analisi",
        errorDescription: "Impossibile analizzare il pasto. Riprova.",
        resultsTitle: "Risultati Analisi Nutrizionale",
        estimatedCalories: "Calorie Stimate",
        protein: "Proteine (g)",
        carbs: "Carboidrati (g)",
        fat: "Grassi (g)",
        generalAdvice: "Consigli Generali",
        noPhotoSelected: "Nessuna foto selezionata",
    },
    settingsPage: {
      title: 'Impostazioni',
      language: 'Lingua',
      selectLanguage: 'Seleziona lingua',
      english: 'English (US)',
      italian: 'Italiano (Italian)',
      spanish: 'Español (Spanish)',
      french: 'Français (French)',
      notifications: 'Notifiche',
      allNotificationsLabel: 'Abilita Tutte le Notifiche dell\'App',
      saveChanges: 'Salva Modifiche',
      settingsSaved: 'Impostazioni Salvate',
      preferencesUpdated: 'Le tue preferenze sono state aggiornate',
      profileInformationTitle: 'Informazioni Profilo',
      uploadProfilePictureLabel: 'Immagine Profilo',
      profilePictureAlt: 'Immagine del Profilo',
      photoSizeError: 'La dimensione della foto non deve superare i 2MB.',
      photoSizeLimit: 'Max 2MB. Formato quadrato consigliato.',
      nameLabel: 'Nome',
      namePlaceholder: 'Inserisci il tuo nome',
      emailLabel: 'Email',
      emailCannotBeChanged: 'L\'email non può essere modificata qui.',
      accountSecurityTitle: 'Sicurezza Account',
      currentPasswordLabel: 'Password Attuale',
      newPasswordLabel: 'Nuova Password',
      newPasswordPlaceholder: 'Inserisci nuova password (min. 8 caratteri)',
      confirmNewPasswordLabel: 'Conferma Nuova Password',
      confirmNewPasswordPlaceholder: 'Conferma nuova password',
      passwordMismatchError: 'Le nuove password non coincidono.',
      passwordChangedTitle: 'Password Modificata',
      passwordChangedSuccess: 'La tua password è stata aggiornata con successo.',
      currentPasswordRequiredError: 'La password attuale è richiesta per impostarne una nuova.',
      noChangesMadeTitle: 'Nessuna Modifica',
      noChangesMadeDescription: 'Nessuna impostazione è stata modificata.',
      toastErrorTitle: 'Errore',
      showPassword: 'Mostra password',
      hidePassword: 'Nascondi password',
      currentWeightLabel: 'Peso Attuale (kg)',
      currentWeightPlaceholder: 'es. 70.5',
    },
    aiSplitForm: {
        cardTitle: "Consulente Fitness AI",
        cardDescription: "Ottieni consigli di allenamento personalizzati dal nostro coach AI. Il tuo storico allenamenti recente verrà analizzato automaticamente insieme ai tuoi obiettivi.",
        trainingHistoryAutoCollectedInfo: "Il tuo storico allenamenti recente viene raccolto automaticamente per fornire consigli personalizzati.",
        trainingGoalsLabel: "Obiettivi di Allenamento",
        trainingGoalsPlaceholder: "es., Vorrei aumentare la massa muscolare, migliorare la forza nei composti e aumentare la resistenza generale. Voglio far crescere gambe e spalle.",
        trainingGoalsDescription: "Cosa vuoi ottenere con il tuo allenamento? (es. aumento massa, perdita grasso, aumento forza)",
        trainingGoalsMinError: "Descrivi i tuoi obiettivi di allenamento (almeno 10 caratteri).",
        getAISuggestionButton: "Ottieni Consigli AI",
        generatingSplitTitle: "Sto generando i tuoi consigli...",
        generatingSplitDescription: "La nostra AI sta elaborando. Potrebbe volerci un momento.",
        yourSuggestedAdviceTitle: "I Tuoi Consigli dal Coach AI",
        suggestedKeyPointsLabel: "Suggerimenti Chiave:",
        detailedAnalysisLabel: "Analisi Dettagliata e Consigli:",
        toastSuggestionReadyTitle: "Consigli Pronti!",
        toastSuggestionReadyDescription: "L'AI ha generato consigli di allenamento per te.",
        toastErrorTitle: "Errore",
        toastErrorDescription: "Impossibile ottenere i consigli AI. Riprova.",
        errorFetchingHistory: "Impossibile recuperare automaticamente il tuo storico allenamenti. Assicurati di avere degli allenamenti registrati.",
    },
    calendarPage: {
        title: "Calendario Allenamenti",
        description: "Pianifica e monitora il tuo programma di allenamento settimanale.",
        selectADate: "Seleziona una Data",
        workoutsScheduledForThisDay: "Allenamenti programmati per questo giorno.",
        addWorkoutToDay: "Aggiungi Allenamento",
        noWorkoutsScheduled: "Nessun allenamento programmato per questo giorno.",
        selectDateToSeeWorkouts: "Seleziona una data per vedere gli allenamenti programmati.",
        dialogAddWorkoutTitle: "Aggiungi Allenamento a {dayOfWeek}",
        dialogAddWorkoutDescription: "Seleziona una scheda di allenamento da programmare per questo giorno della settimana.",
        workoutPlanLabel: "Scheda Allenamento",
        selectAPlanPlaceholder: "Seleziona una scheda",
        samplePlan1: "Scheda Total Body",
        samplePlan2: "Scheda Parte Superiore",
        samplePlan3: "Scheda Gambe Intensa",
        samplePlan4: "Sessione Cardio",
        cancelButton: "Annulla",
        scheduleWorkoutButton: "Programma Allenamento",
        loadingCalendar: "Caricamento calendario...",
        weeklyScheduleTitle: "Programma Allenamento Settimanale",
        weeklyScheduleDescription: "Imposta la tua settimana di allenamento tipo. Questo programma si ripeterà automaticamente.",
        days: {
          monday: "Lunedì",
          tuesday: "Martedì",
          wednesday: "Mercoledì",
          thursday: "Giovedì",
          friday: "Venerdì",
          saturday: "Sabato",
          sunday: "Domenica",
        },
        noWorkoutsForDayOfWeek: "Nessun allenamento programmato per {dayOfWeek}.",
        addWorkoutTo: "Aggiungi a {dayOfWeek}",
        toastWorkoutScheduledTitle: "Allenamento Programmato!",
        toastWorkoutScheduledDescriptionNoTime: "{planName} il {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Allenamento Rimosso",
        errorSelectDayAndPlan: "Seleziona un giorno e una scheda di allenamento.",
        errorPlanNotFound: "Scheda selezionata non trovata.",
    },
    exercisesPage: {
        title: "Esercizi Personalizzati",
        description: "Gestisci la tua libreria di esercizi personalizzati.",
        addNewExerciseButton: "Aggiungi Nuovo Esercizio",
        yourExercisesCardTitle: "I Tuoi Esercizi",
        tableHeaderName: "Nome",
        tableHeaderMuscleGroup: "Gruppo Muscolare",
        tableHeaderType: "Tipo",
        tableHeaderActions: "Azioni",
        dialogAddTitle: "Aggiungi Nuovo Esercizio",
        dialogAddDescription: "Inserisci i dettagli per il tuo nuovo esercizio.",
        dialogEditTitle: "Modifica Esercizio",
        dialogEditDescription: "Aggiorna i dettagli del tuo esercizio.",
        formNameLabel: "Nome",
        formDescriptionLabel: "Descrizione",
        formMuscleGroupLabel: "Gruppo Muscolare",
        selectMuscleGroupPlaceholder: "Seleziona gruppo muscolare",
        muscleGroupChest: "Petto",
        muscleGroupBack: "Schiena",
        muscleGroupLegs: "Gambe",
        muscleGroupShoulders: "Spalle",
        muscleGroupBiceps: "Bicipiti",
        muscleGroupTriceps: "Tricipiti",
        muscleGroupAbs: "Addominali",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Altro",
        formTypeLabel: "Tipo",
        selectExerciseTypePlaceholder: "Seleziona tipo di esercizio",
        typeStrength: "Forza",
        typeCardio: "Cardio",
        typeFlexibility: "Flessibilità",
        typePlyometrics: "Pliometria",
        typeOther: "Altro",
        cancelButton: "Annulla",
        saveExerciseButton: "Salva Esercizio",
    },
    progressPage: {
        title: "Monitoraggio Progressi",
        description: "Visualizza il tuo percorso di fitness e celebra i tuoi traguardi.",
        performanceMetricsCardTitle: "Metriche di Performance",
        performanceMetricsCardDescription: "Traccia i tuoi sollevamenti chiave e misurazioni nel tempo.",
        weeklyTrainingVolumeLabel: "Volume Allenamento Settimanale (kg)",
        benchPressLabel: "Panca Piana (kg)",
        squatLabel: "Squat (kg)",
        bodyCompositionCardTitle: "Composizione Corporea",
        bodyCompositionCardDescription: "Monitora i cambiamenti di peso, grasso corporeo, ecc.",
        weightLabel: "Peso (kg)",
        photoComparisonCardTitle: "Confronto Foto",
        photoComparisonCardDescription: "Traccia visivamente la tua trasformazione. Carica foto 'prima' e 'dopo'.",
        beforePhotoLabel: "Foto Prima",
        afterPhotoLabel: "Foto Dopo",
        noPhotoUploaded: "Nessuna foto caricata",
        clickToUpload: "Clicca per caricare",
        uploadButtonLabel: "Carica",
        bodyMeasurementsCardTitle: "Misure Corporee",
        bodyMeasurementsCardDescription: "Traccia le tue misure corporee come peso, altezza e circonferenze muscolari nel tempo.",
        addMeasurementButton: "Aggiungi Misura",
        measurementDialogAddTitle: "Aggiungi Nuova Misura",
        measurementDialogEditTitle: "Modifica Misura",
        measurementDialogDescription: "Inserisci i dettagli per la tua misurazione.",
        formDateLabel: "Data",
        formMeasurementNameLabel: "Tipo Misurazione",
        selectMeasurementNamePlaceholder: "Seleziona tipo misurazione",
        measurementNameBiceps: "Bicipiti",
        measurementNameChest: "Petto",
        measurementNameWaist: "Vita",
        measurementNameHips: "Fianchi",
        measurementNameThigh: "Coscia",
        measurementNameCalf: "Polpaccio",
        measurementNameWeight: "Peso",
        measurementNameHeight: "Altezza",
        formValueLabel: "Valore",
        formUnitLabel: "Unità",
        unitCM: "cm",
        unitIN: "pollici",
        unitKG: "kg",
        unitLBS: "libbre",
        formNotesLabel: "Note",
        formNotesPlaceholder: "Inserisci eventuali note pertinenti...",
        saveMeasurementButton: "Salva Misura",
        tableHeaderDate: "Data",
        tableHeaderMeasurementName: "Misurazione",
        tableHeaderValue: "Valore",
        measurementReminderLabel: "Promemoria Misurazioni",
        selectReminderFrequencyPlaceholder: "Seleziona frequenza promemoria",
        reminderOff: "Spento",
        reminderDaily: "Giornaliero",
        reminderWeekly: "Settimanale",
        reminderBiWeekly: "Bisettimanale",
        reminderMonthly: "Mensile",
        measurementSaved: "Misura Salvata",
        measurementDeleted: "Misura Eliminata",
        noMeasurementsYet: "Nessuna misura registrata. Aggiungi la prima!",
        formValidationAlert: "Compila data, tipo misurazione e valore.",
    },
     workoutPlansPage: {
        title: "Schede Allenamento",
        description: "Crea, gestisci e condividi i tuoi programmi di allenamento.",
        createNewPlanButton: "Crea Nuova Scheda",
        exercisesLabel: "Esercizi",
        estDurationLabel: "Durata Stimata",
        startButton: "Inizia",
        dialogEditTitle: "Modifica Scheda Allenamento",
        dialogEditDescription: "Aggiorna i dettagli della tua scheda di allenamento.",
        dialogCreateTitle: "Crea Nuova Scheda Allenamento",
        dialogCreateDescription: "Progetta la tua nuova scheda di allenamento.",
        planNameLabel: "Nome Scheda",
        descriptionLabel: "Descrizione",
        exerciseNameLabel: "Nome Esercizio",
        setsLabel: "Serie",
        repsLabel: "Ripetizioni",
        addThisExerciseButton: "Aggiungi Esercizio",
        addedExercisesLabel: "Esercizi Aggiunti:",
        noExercisesAddedYet: "Nessun esercizio aggiunto a questa scheda.",
        exerciseSelectionPlaceholder: "Aggiungi esercizi a questa scheda usando il modulo sopra.",
        addExerciseButton: "Aggiungi Esercizio alla Scheda",
        cancelButton: "Annulla",
        savePlanButton: "Salva Scheda",
        toastPlanUpdatedTitle: "Scheda Aggiornata",
        toastPlanUpdatedDescription: "La scheda \"{planName}\" è stata aggiornata.",
        toastPlanCreatedTitle: "Scheda Creata",
        toastPlanCreatedDescription: "La scheda \"{planName}\" è stata creata.",
        toastPlanDeletedTitle: "Scheda Eliminata",
        toastPlanDeletedDescription: "La scheda \"{planName}\" è stata eliminata.",
        toastLinkCopiedTitle: "Link Copiato!",
        toastLinkCopiedDescription: "Link della scheda di allenamento copiato negli appunti.",
        muscleSilhouetteAlt: "Gruppi muscolari coinvolti nella scheda",
        muscleGroupsLabel: "Gruppi Muscolari",
    },
    startWorkoutPage: {
      title: "Inizia Nuovo Allenamento",
      description: "Scegli una scheda da iniziare o avvia una sessione libera.",
      selectPlanTitle: "Seleziona una Scheda",
      startAdHocButton: "Inizia Allenamento Libero",
      noPlansAvailable: "Nessuna scheda di allenamento disponibile. Creane una prima!",
      startPlanButton: "Inizia Scheda",
    },
    activeWorkoutPage: {
      title: "Allenamento Attivo: {planName}",
      description: "Traccia serie, ripetizioni e pesi per questa sessione.",
      finishWorkoutButton: "Termina Allenamento",
      logSetButton: "Registra Serie",
      planNotFound: "Scheda di allenamento non trovata.",
      planNotFoundDescription: "Controlla l'URL o torna indietro per selezionare una scheda valida.",
      loadingWorkout: "Caricamento Allenamento...",
      loadingDescription: "Attendere prego, stiamo caricando i dettagli della scheda.",
      targetSetsLabel: "Serie Obiettivo",
      targetRepsLabel: "Ripetizioni Obiettivo",
      repsInputLabel: "Ripetizioni",
      weightInputLabel: "Peso (kg)",
      setColumnLabel: "Serie",
      dateColumnLabel: "Data",
      repsColumnLabel: "Ripetizioni",
      weightColumnLabel: "Peso (kg)",
      toastSetLoggedTitle: "Serie Registrata",
      toastSetLoggedDescription: "Serie per {exerciseName} registrata.",
      toastSetDeletedTitle: "Serie Eliminata",
      toastWorkoutFinishedTitle: "Allenamento Terminato!",
      toastWorkoutFinishedDescription: "Ottimo lavoro! Hai completato l'allenamento in {duration}!",
      overallProgressLabel: "Progresso Allenamento Complessivo",
      setCompletionLabel: "Serie: {completed}/{total}",
      noGifAvailable: "Nessun GIF disponibile",
      exerciseDemoAlt: "dimostrazione esercizio",
      nextExerciseButton: "Prossimo Esercizio",
      completeWorkoutButton: "Completa Allenamento",
      workoutCompleteTitle: "Allenamento Completato!",
      workoutCompleteDescription: "Hai completato con successo l'allenamento {planName}.",
      totalTimeLabel: "Tempo Totale",
      backToDashboardButton: "Torna alla Home",
      confirmFinishTitle: "Terminare Allenamento?",
      confirmFinishDescription: "Sei sicuro di voler contrassegnare questo allenamento come completato?",
      confirmFinishButton: "Sì, Termina",
      noSetsLoggedYet: "Nessuna serie registrata per questo esercizio.",
      sessionPBsLabel: "PB Sessione",
      maxWeightLabel: "Peso Max",
      maxRepsLabel: "Rip. Max",
      repsUnitLabel: "rip.",
      workoutInProgressTitle: "Allenamento in Corso",
      finishCurrentWorkoutPrompt: "Hai un allenamento attivo. Per favore, terminalo o abbandonalo prima di iniziarne uno nuovo o creare/modificare schede.",
    },
    dietPage: {
        title: "Monitoraggio Dieta",
        description: "Gestisci il tuo apporto nutrizionale giornaliero e l'idratazione.",
    },
    toastErrorTitle: "Errore",
    resumeWorkoutButton: {
      resumeTitle: "Riprendi Allenamento",
      resume: "Riprendi: {planName}",
    }
  },
  es: {
    nav: {
      dashboard: 'Inicio',
      exercises: 'Ejercicios',
      workoutPlans: 'Planes de Entrenamiento',
      calendar: 'Calendario',
      progress: 'Progreso',
      diet: 'Dieta',
    },
    userDropdown: {
        myAccount: 'Mi Cuenta',
        settings: 'Configuración',
        theme: 'Tema',
        light: 'Claro',
        dark: 'Oscuro',
        system: 'Sistema',
        logout: 'Cerrar Sesión',
    },
    header: {
        toggleTheme: 'Cambiar tema',
    },
     dashboard: {
      welcomeTitle: '¡Bienvenido a SickFit Pro!',
      welcomeDescription: "Tu viaje hacia la máxima forma física comienza aquí. ¡Manos a la obra!",
      workoutsThisWeek: 'Entrenamientos Esta Semana',
      weightLifted: 'Peso Total Levantado',
      currentWeight: 'Peso Actual',
      logNewWorkout: 'Empezar Entrenamiento',
      todaysFocus: "Enfoque de Hoy",
      todaysFocusDescription: "¿Qué hay en la agenda para hoy?",
      checkCalendarForWorkout: "¡Revisa tu calendario para el entrenamiento de hoy!",
      viewCalendarToSeeWorkout: "Tu entrenamiento programado aparecerá aquí.",
      viewFullSchedule: 'Ver Horario Completo',
      activityAndHistoryTitle: "Actividad e Historial",
      activityAndHistoryDescription: "Comienza un nuevo entrenamiento o revisa tus sesiones pasadas.",
      noWorkoutHistory: "Aún no hay historial de entrenamientos. ¡Completa un entrenamiento para verlo aquí!",
      viewAllHistoryButton: "Ver Todo el Historial",
      todayIsRestDay: "¡Hoy es día de descanso! ¡Disfrútalo! 😊",
      noWorkoutScheduledForToday: "Ningún entrenamiento programado para hoy.",
    },
    settingsPage: {
      title: 'Configuración',
      language: 'Idioma',
      selectLanguage: 'Seleccionar idioma',
      english: 'Inglés (EE. UU.)',
      italian: 'Italiano',
      spanish: 'Español',
      french: 'Francés',
      notifications: 'Notificaciones',
      allNotificationsLabel: 'Habilitar Todas las Notificaciones de la App',
      saveChanges: 'Guardar Cambios',
      settingsSaved: 'Configuración Guardada',
      preferencesUpdated: 'Tus preferencias han sido actualizadas',
      profileInformationTitle: 'Información del Perfil',
      uploadProfilePictureLabel: 'Foto de Perfil',
      profilePictureAlt: 'Foto de Perfil',
      photoSizeError: 'El tamaño de la foto no debe exceder los 2MB.',
      photoSizeLimit: 'Máx 2MB. Se recomienda relación de aspecto cuadrada.',
      nameLabel: 'Nombre',
      namePlaceholder: 'Introduce tu nombre',
      emailLabel: 'Correo Electrónico',
      emailCannotBeChanged: 'El correo electrónico no se puede cambiar aquí.',
      accountSecurityTitle: 'Seguridad de la Cuenta',
      currentPasswordLabel: 'Contraseña Actual',
      newPasswordLabel: 'Nueva Contraseña',
      newPasswordPlaceholder: 'Introduce nueva contraseña (mín. 8 caracteres)',
      confirmNewPasswordLabel: 'Confirmar Nueva Contraseña',
      confirmNewPasswordPlaceholder: 'Confirma la nueva contraseña',
      passwordMismatchError: 'Las nuevas contraseñas no coinciden.',
      passwordChangedTitle: 'Contraseña Cambiada',
      passwordChangedSuccess: 'Tu contraseña ha sido actualizada correctamente.',
      currentPasswordRequiredError: 'Se requiere la contraseña actual para establecer una nueva.',
      noChangesMadeTitle: 'Sin Cambios',
      noChangesMadeDescription: 'No se modificó ninguna configuración.',
      toastErrorTitle: 'Error',
      showPassword: 'Mostrar contraseña',
      hidePassword: 'Ocultar contraseña',
      currentWeightLabel: 'Peso Actual (kg)',
      currentWeightPlaceholder: 'ej. 70.5',
    },
    toastErrorTitle: "Error",
    waterIntakeCard: {
      title: "Consumo de Agua",
      description: "¡Mantente hidratado! Tu meta: {dailyGoal} ml.",
      currentIntakeLabel: "Actual: {current}ml / {dailyGoal}ml",
      setGoalLabel: "Establecer Meta Diaria (ml)",
      saveGoalButton: "Guardar Meta",
      reminderLabel: "Recordatorio de Hidratación",
      selectReminderFrequencyPlaceholder: "Frecuencia",
      reminderOff: "Apagado",
      reminderDaily: "Diario",
      reminderHourly: "Cada Hora",
       goalSavedTitle: "Meta Guardada",
      goalSavedDescription: "Tu meta diaria de consumo de agua ha sido actualizada.",
      resetWaterButton: "Reiniciar Agua",
      waterResetTitle: "Agua Reiniciada",
      waterResetDescription: "Tu consumo de agua para el día ha sido reiniciado.",
      ariaAddGlass: "Añadir vaso ({amount}ml)",
      ariaAddBottle: "Añadir botella ({amount}ml)",
      tooltipAddAmount: "+{amount}ml",
    },
    macroTrackingCard: {
        title: "Seguimiento de Macros",
        description: "Controla tu ingesta diaria de proteínas, carbohidratos y grasas.",
        descriptionWeekly: "Planifica tus objetivos de macronutrientes semanales y visualiza las estimaciones mensuales.",
        proteinLabel: "Proteína",
        carbsLabel: "Carbohidratos",
        fatLabel: "Grasa",
        setYourDailyGoals: "Establece Tus Metas Diarias",
        setYourWeeklyGoals: "Establece Tus Metas Semanales de Macros",
        selectDay: "Seleccionar Día",
        logYourDailyIntake: "Registra Tu Ingesta Diaria",
        saveGoalsButton: "Guardar Metas del Día",
        saveIntakeButton: "Guardar Ingesta",
        reminderLabel: "Recordatorio de Macros",
        selectReminderFrequencyPlaceholder: "Frecuencia",
        reminderOff: "Apagado",
        reminderDaily: "Diario",
        reminderMealtime: "Alrededor de Comidas",
         goalsSavedTitle: "Metas de Macros Guardadas",
        goalsSavedDescription: "Tus metas diarias de macronutrientes han sido actualizadas.",
        goalsForDaySaved: "¡Metas para {dayOfWeek} guardadas con éxito!",
        intakeSavedTitle: "Ingesta de Macros Guardada",
        intakeSavedDescription: "Tu ingesta diaria de macronutrientes ha sido registrada.",
        monthlyTotalsTitle: "Totales Mensuales Estimados",
        totalProteinMonth: "Proteína Total (Mes)",
        totalCarbsMonth: "Carbohidratos Totales (Mes)",
        totalFatMonth: "Grasa Total (Mes)",
        unitGrams: "g",
        loadingTotals: "Calculando totales mensuales...",
    },
    nutritionalAnalysis: {
        cardTitle: "Análisis Nutricional (IA)",
        cardDescription: "Describe tu comida o sube una foto para obtener un desglose nutricional y consejos con IA.",
        mealDescriptionLabel: "Descripción de la Comida",
        mealDescriptionPlaceholder: "Ej: Pechuga de pollo a la parrilla con quinoa y brócoli al vapor.",
        mealPhotoLabel: "Foto de la Comida (Opcional)",
        analyzeMealButton: "Analizar Comida",
        resultsTitle: "Resultados del Análisis Nutricional",
        estimatedCalories: "Calorías Estimadas",
        protein: "Proteína (g)",
        carbs: "Carbohidratos (g)",
        fat: "Grasa (g)",
        generalAdvice: "Consejos Generales",
        noPhotoSelected: "Ninguna foto seleccionada",
        uploadPhotoButton: "Subir Foto",
        photoPreviewAlt: "Vista previa de la foto de la comida",
        removePhoto: "Quitar Foto",
        analysisReadyTitle: "¡Análisis Listo!",
        analysisReadyDescription: "El análisis nutricional de tu comida está completo.",
        errorTitle: "Error de Análisis",
        errorDescription: "No se pudo analizar la comida. Por favor, inténtalo de nuevo."
    },
    dietPage: {
        title: "Seguimiento de Dieta",
        description: "Gestiona tu ingesta nutricional diaria y tu hidratación.",
    },
    aiSplitForm: {
        cardTitle: "Asesor Fitness IA",
        cardDescription: "Obtén consejos de entrenamiento personalizados de nuestro entrenador IA. Tu historial de entrenamiento reciente se analizará automáticamente junto con tus objetivos.",
        trainingHistoryAutoCollectedInfo: "Tu historial de entrenamiento reciente se recopila automáticamente para proporcionar consejos personalizados.",
        trainingGoalsLabel: "Objetivos de Entrenamiento",
        trainingGoalsPlaceholder: "Ej: Busco ganar masa muscular, mejorar la fuerza en levantamientos compuestos y aumentar la resistencia general. Específicamente quiero desarrollar mis piernas y hombros.",
        trainingGoalsDescription: "¿Qué quieres lograr con tu entrenamiento? (ej. ganar músculo, perder grasa, aumentar fuerza)",
        trainingGoalsMinError: "Por favor, describe tus objetivos de entrenamiento (al menos 10 caracteres).",
        getAISuggestionButton: "Obtener Consejo IA",
        yourSuggestedAdviceTitle: "Tu Consejo de Fitness IA",
        suggestedKeyPointsLabel: "Sugerencias Clave:",
        detailedAnalysisLabel: "Análisis Detallado y Consejos:",
        toastSuggestionReadyTitle: "¡Consejo Listo!",
        toastSuggestionReadyDescription: "La IA ha generado consejos de entrenamiento para ti.",
        toastErrorTitle: "Error",
        toastErrorDescription: "Error al obtener el consejo de la IA. Inténtalo de nuevo.",
        errorFetchingHistory: "No se pudo recuperar automáticamente tu historial de entrenamiento. Asegúrate de tener algunos entrenamientos registrados.",
        generatingSplitTitle: "Generando tu consejo...",
        generatingSplitDescription: "Nuestra IA está pensando. Esto podría tomar un momento.",
    },
    calendarPage: {
        title: "Calendario de Entrenamientos",
        description: "Planifica y sigue tu horario de entrenamiento semanal.",
        weeklyScheduleTitle: "Horario Semanal de Entrenamiento",
        weeklyScheduleDescription: "Configura tu semana de entrenamiento típica. Este horario se repetirá automáticamente.",
        days: {
          monday: "Lunes",
          tuesday: "Martes",
          wednesday: "Miércoles",
          thursday: "Jueves",
          friday: "Viernes",
          saturday: "Sábado",
          sunday: "Domingo",
        },
        noWorkoutsForDayOfWeek: "No hay entrenamientos programados para {dayOfWeek}.",
        addWorkoutToDay: "Añadir Entrenamiento",
        cancelButton: "Cancelar",
        scheduleWorkoutButton: "Programar Entrenamiento",
        workoutPlanLabel: "Plan de Entrenamiento",
        selectAPlanPlaceholder: "Selecciona un plan",
        dialogAddWorkoutTitle: "Añadir Entrenamiento a {dayOfWeek}",
        dialogAddWorkoutDescription: "Selecciona un plan de entrenamiento para programar para este día de la semana.",
        toastWorkoutScheduledTitle: "¡Entrenamiento Programado!",
        toastWorkoutScheduledDescriptionNoTime: "{planName} el {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Entrenamiento Eliminado",
        errorSelectDayAndPlan: "Por favor, selecciona un día y un plan de entrenamiento.",
        errorPlanNotFound: "Plan seleccionado no encontrado.",
        samplePlan1: "Explosión de Cuerpo Completo",
        samplePlan2: "Poder del Tren Superior",
        samplePlan3: "Dominación del Día de Piernas",
        samplePlan4: "Sesión de Cardio",
        loadingCalendar: "Cargando calendario...",
    },
     exercisesPage: {
        title: "Ejercicios Personalizados",
        description: "Gestiona tu biblioteca de ejercicios personalizados.",
        addNewExerciseButton: "Añadir Nuevo Ejercicio",
        yourExercisesCardTitle: "Tus Ejercicios",
        tableHeaderName: "Nombre",
        tableHeaderMuscleGroup: "Grupo Muscular",
        tableHeaderType: "Tipo",
        tableHeaderActions: "Acciones",
        dialogAddTitle: "Añadir Nuevo Ejercicio",
        dialogAddDescription: "Completa los detalles de tu nuevo ejercicio.",
        dialogEditTitle: "Editar Ejercicio",
        dialogEditDescription: "Actualiza los detalles de tu ejercicio.",
        formNameLabel: "Nombre",
        formDescriptionLabel: "Descripción",
        formMuscleGroupLabel: "Grupo Muscular",
        selectMuscleGroupPlaceholder: "Selecciona grupo muscular",
        muscleGroupChest: "Pecho",
        muscleGroupBack: "Espalda",
        muscleGroupLegs: "Piernas",
        muscleGroupShoulders: "Hombros",
        muscleGroupBiceps: "Bíceps",
        muscleGroupTriceps: "Tríceps",
        muscleGroupAbs: "Abdominales",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Otro",
        formTypeLabel: "Tipo",
        selectExerciseTypePlaceholder: "Selecciona tipo de ejercicio",
        typeStrength: "Fuerza",
        typeCardio: "Cardio",
        typeFlexibility: "Flexibilidad",
        typePlyometrics: "Pliométricos",
        typeOther: "Otro",
        cancelButton: "Cancelar",
        saveExerciseButton: "Guardar Ejercicio",
    },
    progressPage: {
        title: "Seguimiento de Progreso",
        description: "Visualiza tu viaje de fitness y celebra tus logros.",
        performanceMetricsCardTitle: "Métricas de Rendimiento",
        performanceMetricsCardDescription: "Haz un seguimiento de tus levantamientos clave y mediciones a lo largo del tiempo.",
        weeklyTrainingVolumeLabel: "Volumen Semanal de Entrenamiento (kg)",
        bodyCompositionCardTitle: "Composición Corporal",
        bodyCompositionCardDescription: "Monitorea los cambios en peso, grasa corporal, etc.",
        weightLabel: "Peso (kg)",
        photoComparisonCardTitle: "Comparación de Fotos",
        photoComparisonCardDescription: "Sigue visualmente tu transformación. Sube fotos de 'antes' y 'después'.",
        beforePhotoLabel: "Foto Antes",
        afterPhotoLabel: "Foto Después",
        noPhotoUploaded: "No se ha subido ninguna foto",
        clickToUpload: "Haz clic para subir",
        uploadButtonLabel: "Subir",
        bodyMeasurementsCardTitle: "Medidas Corporales",
        bodyMeasurementsCardDescription: "Haz un seguimiento de tus medidas corporales como peso, altura y tamaño muscular a lo largo del tiempo.",
        addMeasurementButton: "Añadir Medida",
        measurementDialogAddTitle: "Añadir Nueva Medida",
        measurementDialogEditTitle: "Editar Medida",
        measurementDialogDescription: "Introduce los detalles de tu medida.",
        formDateLabel: "Fecha",
        formMeasurementNameLabel: "Tipo de Medida",
        selectMeasurementNamePlaceholder: "Selecciona tipo de medida",
        measurementNameBiceps: "Bíceps",
        measurementNameChest: "Pecho",
        measurementNameWaist: "Cintura",
        measurementNameHips: "Caderas",
        measurementNameThigh: "Muslo",
        measurementNameCalf: "Pantorrilla",
        measurementNameWeight: "Peso",
        measurementNameHeight: "Altura",
        formValueLabel: "Valor",
        unitCM: "cm",
        unitIN: "pulgadas",
        unitKG: "kg",
        unitLBS: "libras",
        formNotesLabel: "Notas",
        formNotesPlaceholder: "Introduce notas relevantes...",
        saveMeasurementButton: "Guardar Medida",
        tableHeaderDate: "Fecha",
        tableHeaderMeasurementName: "Medida",
        tableHeaderValue: "Valor",
        measurementReminderLabel: "Recordatorio de Medidas",
        selectReminderFrequencyPlaceholder: "Selecciona frecuencia",
        reminderOff: "Desactivado",
        reminderDaily: "Diario",
        reminderWeekly: "Semanal",
        reminderBiWeekly: "Quincenal",
        reminderMonthly: "Mensual",
        measurementSaved: "Medida Guardada",
        measurementDeleted: "Medida Eliminada",
        noMeasurementsYet: "Aún no hay medidas registradas. ¡Añade la primera!",
        formValidationAlert: "Por favor, completa la fecha, el tipo de medida y el valor.",
    },
    workoutPlansPage: {
        title: "Planes de Entrenamiento",
        description: "Crea, gestiona y comparte tus horarios de entrenamiento.",
        createNewPlanButton: "Crear Nuevo Plan",
        exercisesLabel: "Ejercicios",
        estDurationLabel: "Duración Estimada",
        startButton: "Empezar",
        dialogEditTitle: "Editar Plan de Entrenamiento",
        dialogEditDescription: "Actualiza los detalles de tu plan de entrenamiento.",
        dialogCreateTitle: "Crear Nuevo Plan de Entrenamiento",
        dialogCreateDescription: "Diseña tu nuevo plan de entrenamiento.",
        planNameLabel: "Nombre del Plan",
        descriptionLabel: "Descripción",
        exerciseNameLabel: "Nombre del Ejercicio",
        setsLabel: "Series",
        repsLabel: "Repeticiones",
        addThisExerciseButton: "Añadir este Ejercicio",
        addedExercisesLabel: "Ejercicios Añadidos:",
        noExercisesAddedYet: "Aún no se han añadido ejercicios a este plan.",
        cancelButton: "Cancelar",
        savePlanButton: "Guardar Plan",
        toastPlanUpdatedTitle: "Plan Actualizado",
        toastPlanUpdatedDescription: '"{planName}" ha sido actualizado.',
        toastPlanCreatedTitle: "Plan Creado",
        toastPlanCreatedDescription: '"{planName}" ha sido creado.',
        toastPlanDeletedTitle: "Plan Eliminado",
        toastPlanDeletedDescription: '"{planName}" ha sido eliminado.',
        toastLinkCopiedTitle: "¡Enlace Copiado!",
        toastLinkCopiedDescription: "Enlace del plan de entrenamiento copiado al portapapeles.",
        muscleSilhouetteAlt: "Grupos musculares involucrados en el plan",
        muscleGroupsLabel: "Grupos Musculares",
    },
    startWorkoutPage: {
      title: "Empezar Nuevo Entrenamiento",
      description: "Elige un plan para empezar o inicia una sesión ad-hoc.",
      selectPlanTitle: "Selecciona un Plan",
      noPlansAvailable: "No hay planes de entrenamiento disponibles. ¡Crea uno primero!",
      startPlanButton: "Empezar Plan",
    },
    activeWorkoutPage: {
        title: "Entrenamiento Activo: {planName}",
        description: "Registra tus series, repeticiones y pesos para esta sesión.",
        finishWorkoutButton: "Finalizar Entrenamiento",
        logSetButton: "Registrar Serie",
        planNotFound: "Plan de entrenamiento no encontrado.",
        planNotFoundDescription: "Por favor, comprueba la URL o vuelve para seleccionar un plan válido.",
        loadingWorkout: "Cargando Entrenamiento...",
        loadingDescription: "Por favor, espera mientras cargamos los detalles del plan.",
        targetSetsLabel: "Series Objetivo",
        targetRepsLabel: "Repeticiones Objetivo",
        repsInputLabel: "Repeticiones",
        weightInputLabel: "Peso (kg)",
        setColumnLabel: "Serie",
        dateColumnLabel: "Fecha",
        repsColumnLabel: "Repeticiones",
        weightColumnLabel: "Peso (kg)",
        toastSetLoggedTitle: "Serie Registrada",
        toastSetLoggedDescription: "Serie para {exerciseName} registrada.",
        toastSetDeletedTitle: "Serie Eliminada",
        toastWorkoutFinishedTitle: "¡Entrenamiento Finalizado!",
        toastWorkoutFinishedDescription: "¡Buen trabajo completando tu entrenamiento en {duration}!",
        overallProgressLabel: "Progreso General del Entrenamiento",
        setCompletionLabel: "Series: {completed}/{total}",
        noGifAvailable: "No hay GIF disponible",
        exerciseDemoAlt: "demostración del ejercicio",
        completeWorkoutButton: "Completar Entrenamiento",
        workoutCompleteTitle: "¡Entrenamiento Completado!",
        workoutCompleteDescription: "Has completado con éxito el entrenamiento {planName}.",
        totalTimeLabel: "Tiempo Total",
        backToDashboardButton: "Volver al Inicio",
        confirmFinishTitle: "¿Finalizar Entrenamiento?",
        confirmFinishDescription: "¿Estás seguro de que quieres marcar este entrenamiento como completado?",
        confirmFinishButton: "Sí, Finalizar",
        noSetsLoggedYet: "Aún no hay series registradas para este ejercicio.",
        sessionPBsLabel: "RPs de Sesión",
        maxWeightLabel: "Peso Máx.",
        maxRepsLabel: "Rep. Máx.",
        repsUnitLabel: "reps",
        workoutInProgressTitle: "Entrenamiento en Curso",
        finishCurrentWorkoutPrompt: "Tienes un entrenamiento activo. Por favor, termínalo o abandónalo antes de empezar uno nuevo o crear/editar planes.",
    },
    resumeWorkoutButton: {
      resumeTitle: "Reanudar Entrenamiento",
      resume: "Reanudar: {planName}",
    }
  },
  fr: {
    nav: {
      dashboard: 'Accueil',
      exercises: 'Exercices',
      workoutPlans: 'Programmes',
      calendar: 'Calendrier',
      progress: 'Progrès',
      diet: 'Diète',
    },
    userDropdown: {
        myAccount: 'Mon Compte',
        settings: 'Paramètres',
        theme: 'Thème',
        light: 'Clair',
        dark: 'Sombre',
        system: 'Système',
        logout: 'Déconnexion',
    },
    header: {
        toggleTheme: 'Changer de thème',
    },
     dashboard: {
      welcomeTitle: 'Bienvenue sur SickFit Pro !',
      welcomeDescription: "Votre parcours vers une forme optimale commence ici. Mettons-nous au travail.",
      workoutsThisWeek: 'Entraînements Cette Semaine',
      weightLifted: 'Poids Total Soulevé',
      currentWeight: 'Poids Actuel',
      logNewWorkout: 'Commencer l\'Entraînement',
      todaysFocus: "Focus d'Aujourd'hui",
      todaysFocusDescription: "Qu'y a-t-il au programme aujourd'hui ?",
      checkCalendarForWorkout: "Consultez votre calendrier pour l'entraînement d'aujourd'hui !",
      viewCalendarToSeeWorkout: "Votre entraînement programmé apparaîtra ici.",
      viewFullSchedule: 'Voir le Programme Complet',
      activityAndHistoryTitle: "Activité et Historique",
      activityAndHistoryDescription: "Commencez un nouvel entraînement ou consultez vos sessions passées.",
      noWorkoutHistory: "Aucun historique d'entraînement pour le moment. Terminez un entraînement pour le voir ici !",
      viewAllHistoryButton: "Voir Tout l'Historique",
      todayIsRestDay: "Aujourd'hui, c'est jour de repos ! Profitez-en ! 😊",
      noWorkoutScheduledForToday: "Aucun entraînement programmé pour aujourd'hui.",
    },
    settingsPage: {
      title: 'Paramètres',
      language: 'Langue',
      selectLanguage: 'Sélectionner la langue',
      english: 'Anglais (US)',
      italian: 'Italien',
      spanish: 'Espagnol',
      french: 'Français',
      notifications: 'Notifications',
      allNotificationsLabel: 'Activer Toutes les Notifications de l\'App',
      saveChanges: 'Enregistrer les Modifications',
      settingsSaved: 'Paramètres Enregistrés',
      preferencesUpdated: 'Vos préférences ont été mises à jour',
      profileInformationTitle: 'Informations du Profil',
      uploadProfilePictureLabel: 'Photo de Profil',
      profilePictureAlt: 'Photo de Profil',
      photoSizeError: 'La taille de la photo ne doit pas dépasser 2 Mo.',
      photoSizeLimit: 'Max 2Mo. Format carré recommandé.',
      nameLabel: 'Nom',
      namePlaceholder: 'Entrez votre nom',
      emailLabel: 'E-mail',
      emailCannotBeChanged: 'L\'e-mail ne peut pas être modifié ici.',
      accountSecurityTitle: 'Sécurité du Compte',
      currentPasswordLabel: 'Mot de Passe Actuel',
      newPasswordLabel: 'Nouveau Mot de Passe',
      newPasswordPlaceholder: 'Entrez un nouveau mot de passe (min. 8 caractères)',
      confirmNewPasswordLabel: 'Confirmer le Nouveau Mot de Passe',
      confirmNewPasswordPlaceholder: 'Confirmez le nouveau mot de passe',
      passwordMismatchError: 'Les nouveaux mots de passe ne correspondent pas.',
      passwordChangedTitle: 'Mot de Passe Modifié',
      passwordChangedSuccess: 'Votre mot de passe a été mis à jour avec succès.',
      currentPasswordRequiredError: 'Le mot de passe actuel est requis pour en définir un nouveau.',
      noChangesMadeTitle: 'Aucun Changement',
      noChangesMadeDescription: 'Aucun paramètre n\'a été modifié.',
      toastErrorTitle: 'Erreur',
      showPassword: 'Afficher le mot de passe',
      hidePassword: 'Masquer le mot de passe',
      currentWeightLabel: 'Poids Actuel (kg)',
      currentWeightPlaceholder: 'ex: 70.5',
    },
    toastErrorTitle: "Erreur",
    waterIntakeCard: {
      title: "Apport en Eau",
      description: "Restez hydraté ! Votre objectif : {dailyGoal} ml.",
      currentIntakeLabel: "Actuel: {current}ml / {dailyGoal}ml",
      setGoalLabel: "Définir l'Objectif Quotidien (ml)",
      saveGoalButton: "Sauvegarder",
      reminderLabel: "Rappel d'Hydratation",
      selectReminderFrequencyPlaceholder: "Fréquence",
      reminderOff: "Désactivé",
      reminderDaily: "Quotidien",
      reminderHourly: "Toutes les heures",
      goalSavedTitle: "Objectif Sauvegardé",
      goalSavedDescription: "Votre objectif quotidien d'apport en eau a été mis à jour.",
      resetWaterButton: "Réinitialiser l'Eau",
      waterResetTitle: "Eau Réinitialisée",
      waterResetDescription: "Votre apport en eau pour la journée a été réinitialisé.",
      ariaAddGlass: "Ajouter un verre ({amount}ml)",
      ariaAddBottle: "Ajouter une bouteille ({amount}ml)",
      tooltipAddAmount: "+{amount}ml",
    },
    macroTrackingCard: {
        title: "Suivi des Macros",
        description: "Surveillez votre apport quotidien en protéines, glucides et lipides.",
        descriptionWeekly: "Planifiez vos objectifs hebdomadaires de macronutriments et consultez les estimations mensuelles.",
        proteinLabel: "Protéines",
        carbsLabel: "Glucides",
        fatLabel: "Lipides",
        setYourDailyGoals: "Définissez Vos Objectifs Quotidiens",
        setYourWeeklyGoals: "Définissez Vos Objectifs Hebdomadaires de Macros",
        selectDay: "Sélectionner Jour",
        logYourDailyIntake: "Enregistrez Votre Apport Quotidien",
        saveGoalsButton: "Sauvegarder Objectifs du Jour",
        saveIntakeButton: "Sauvegarder Apport",
        reminderLabel: "Rappel Suivi Macros",
        selectReminderFrequencyPlaceholder: "Fréquence",
        reminderOff: "Désactivé",
        reminderDaily: "Quotidien",
        reminderMealtime: "Autour des Repas",
        goalsSavedTitle: "Objectifs Macros Sauvegardés",
        goalsSavedDescription: "Vos objectifs quotidiens en macronutriments ont été mis à jour.",
        goalsForDaySaved: "Objectifs pour {dayOfWeek} sauvegardés avec succès !",
        intakeSavedTitle: "Apport Macros Sauvegardé",
        intakeSavedDescription: "Votre apport quotidien en macronutriments a été enregistré.",
        monthlyTotalsTitle: "Totaux Mensuels Estimés",
        totalProteinMonth: "Protéines Totales (Mois)",
        totalCarbsMonth: "Glucides Totals (Mois)",
        totalFatMonth: "Lipides Totals (Mois)",
        unitGrams: "g",
        loadingTotals: "Calcul des totaux mensuels...",
    },
    nutritionalAnalysis: {
        cardTitle: "Analyse Nutritionnelle (IA)",
        cardDescription: "Décrivez votre repas ou téléchargez une photo pour obtenir une analyse nutritionnelle et des conseils basés sur l'IA.",
        mealDescriptionLabel: "Description du Repas",
        mealDescriptionPlaceholder: "Ex: Poitrine de poulet grillée avec quinoa et brocoli vapeur.",
        mealPhotoLabel: "Photo du Repas (Optionnel)",
        analyzeMealButton: "Analyser le Repas",
        resultsTitle: "Résultats de l'Analyse Nutritionnelle",
        estimatedCalories: "Calories Estimées",
        protein: "Protéines (g)",
        carbs: "Glucides (g)",
        fat: "Lipides (g)",
        generalAdvice: "Conseils Généraux",
        noPhotoSelected: "Aucune photo sélectionnée",
        uploadPhotoButton: "Télécharger Photo",
        photoPreviewAlt: "Aperçu de la photo du repas",
        removePhoto: "Supprimer Photo",
        analysisReadyTitle: "Analyse Prête !",
        analysisReadyDescription: "L'analyse nutritionnelle de votre repas est terminée.",
        errorTitle: "Erreur d'Analyse",
        errorDescription: "Impossible d'analyser le repas. Veuillez réessayer."
    },
    dietPage: {
        title: "Suivi de l'Alimentation",
        description: "Gérez votre apport nutritionnel quotidien et votre hydratation.",
    },
    aiSplitForm: {
        cardTitle: "Conseiller Fitness IA",
        cardDescription: "Obtenez des conseils d'entraînement personnalisés de notre coach IA. Votre historique d'entraînement récent sera automatiquement analysé avec vos objectifs.",
        trainingHistoryAutoCollectedInfo: "Votre historique d'entraînement récent est collecté automatiquement pour fournir des conseils personnalisés.",
        trainingGoalsLabel: "Objectifs d'Entraînement",
        trainingGoalsPlaceholder: "Ex: Je cherche à gagner de la masse musculaire, améliorer ma force sur les mouvements composés et augmenter mon endurance générale. Je veux spécifiquement développer mes jambes et mes épaules.",
        trainingGoalsDescription: "Que voulez-vous atteindre avec votre entraînement ? (ex. gain musculaire, perte de graisse, augmentation de la force)",
        trainingGoalsMinError: "Veuillez décrire vos objectifs d'entraînement (au moins 10 caractères).",
        getAISuggestionButton: "Obtenir Conseil IA",
        yourSuggestedAdviceTitle: "Votre Conseil Fitness IA",
        suggestedKeyPointsLabel: "Suggestions Clés :",
        detailedAnalysisLabel: "Analyse Détaillée et Conseils :",
        toastSuggestionReadyTitle: "Conseil Prêt !",
        toastSuggestionReadyDescription: "L'IA a généré des conseils d'entraînement pour vous.",
        toastErrorTitle: "Erreur",
        toastErrorDescription: "Échec de l'obtention du conseil IA. Veuillez réessayer.",
        errorFetchingHistory: "Impossible de récupérer automatiquement votre historique d'entraînement. Assurez-vous d'avoir des entraînements enregistrés.",
        generatingSplitTitle: "Génération de vos conseils...",
        generatingSplitDescription: "Notre IA réfléchit. Cela peut prendre un moment.",
    },
    calendarPage: {
        title: "Calendrier d'Entraînement",
        description: "Planifiez et suivez votre programme d'entraînement hebdomadaire.",
        weeklyScheduleTitle: "Programme d'Entraînement Hebdomadaire",
        weeklyScheduleDescription: "Configurez votre semaine d'entraînement type. Ce programme se répétera automatiquement.",
        days: {
          monday: "Lundi",
          tuesday: "Mardi",
          wednesday: "Mercredi",
          thursday: "Jeudi",
          friday: "Vendredi",
          saturday: "Samedi",
          sunday: "Dimanche",
        },
        noWorkoutsForDayOfWeek: "Aucun entraînement programmé pour {dayOfWeek}.",
        addWorkoutToDay: "Ajouter Entraînement",
        cancelButton: "Annuler",
        scheduleWorkoutButton: "Programmer",
        workoutPlanLabel: "Programme d'Entraînement",
        selectAPlanPlaceholder: "Sélectionnez un programme",
        dialogAddWorkoutTitle: "Ajouter Entraînement à {dayOfWeek}",
        dialogAddWorkoutDescription: "Sélectionnez un programme d'entraînement à planifier pour ce jour de la semaine.",
        toastWorkoutScheduledTitle: "Entraînement Programmé !",
        toastWorkoutScheduledDescriptionNoTime: "{planName} le {dayOfWeek}.",
        toastWorkoutRemovedTitle: "Entraînement Supprimé",
        errorSelectDayAndPlan: "Veuillez sélectionner un jour et un programme d'entraînement.",
        errorPlanNotFound: "Programme sélectionné non trouvé.",
        samplePlan1: "Explosion Corps Complet",
        samplePlan2: "Puissance Haut du Corps",
        samplePlan3: "Domination Jour des Jambes",
        samplePlan4: "Séance Cardio",
        loadingCalendar: "Chargement du calendrier...",
    },
    exercisesPage: {
        title: "Exercices Personnalisés",
        description: "Gérez votre bibliothèque d'exercices personnalisés.",
        addNewExerciseButton: "Ajouter un Nouvel Exercice",
        yourExercisesCardTitle: "Vos Exercices",
        tableHeaderName: "Nom",
        tableHeaderMuscleGroup: "Groupe Musculaire",
        tableHeaderType: "Type",
        tableHeaderActions: "Actions",
        dialogAddTitle: "Ajouter un Nouvel Exercice",
        dialogAddDescription: "Remplissez les détails de votre nouvel exercice.",
        dialogEditTitle: "Modifier l'Exercice",
        dialogEditDescription: "Mettez à jour les détails de votre exercice.",
        formNameLabel: "Nom",
        formDescriptionLabel: "Description",
        formMuscleGroupLabel: "Groupe Musculaire",
        selectMuscleGroupPlaceholder: "Sélectionnez un groupe musculaire",
        muscleGroupChest: "Pectoraux",
        muscleGroupBack: "Dos",
        muscleGroupLegs: "Jambes",
        muscleGroupShoulders: "Épaules",
        muscleGroupBiceps: "Biceps",
        muscleGroupTriceps: "Triceps",
        muscleGroupAbs: "Abdominaux",
        muscleGroupCardio: "Cardio",
        muscleGroupOther: "Autre",
        formTypeLabel: "Type",
        selectExerciseTypePlaceholder: "Sélectionnez un type d'exercice",
        typeStrength: "Force",
        typeCardio: "Cardio",
        typeFlexibility: "Flexibilité",
        typePlyometrics: "Pliométrie",
        typeOther: "Autre",
        cancelButton: "Annuler",
        saveExerciseButton: "Enregistrer l'Exercice",
    },
    progressPage: {
        title: "Suivi des Progrès",
        description: "Visualisez votre parcours de fitness et célébrez vos accomplissements.",
        performanceMetricsCardTitle: "Métrique de Performance",
        performanceMetricsCardDescription: "Suivez vos principaux exercices et mesures au fil du temps.",
        weeklyTrainingVolumeLabel: "Volume d'Entraînement Hebdomadaire (kg)",
        bodyCompositionCardTitle: "Composition Corporelle",
        bodyCompositionCardDescription: "Surveillez les changements de poids, de graisse corporelle, etc.",
        weightLabel: "Poids (kg)",
        photoComparisonCardTitle: "Comparaison de Photos",
        photoComparisonCardDescription: "Suivez visuellement votre transformation. Téléchargez des photos 'avant' et 'après'.",
        beforePhotoLabel: "Photo Avant",
        afterPhotoLabel: "Photo Après",
        noPhotoUploaded: "Aucune photo téléchargée",
        clickToUpload: "Cliquez pour télécharger",
        uploadButtonLabel: "Télécharger",
        bodyMeasurementsCardTitle: "Mesures Corporelles",
        bodyMeasurementsCardDescription: "Suivez vos mesures corporelles comme le poids, la taille et la taille des muscles au fil du temps.",
        addMeasurementButton: "Ajouter Mesure",
        measurementDialogAddTitle: "Ajouter Nouvelle Mesure",
        measurementDialogEditTitle: "Modifier Mesure",
        measurementDialogDescription: "Entrez les détails de votre mesure.",
        formDateLabel: "Date",
        formMeasurementNameLabel: "Type de Mesure",
        selectMeasurementNamePlaceholder: "Sélectionnez un type de mesure",
        measurementNameBiceps: "Biceps",
        measurementNameChest: "Pectoraux",
        measurementNameWaist: "Taille",
        measurementNameHips: "Hanches",
        measurementNameThigh: "Cuisse",
        measurementNameCalf: "Mollet",
        measurementNameWeight: "Poids",
        measurementNameHeight: "Taille (hauteur)",
        formValueLabel: "Valeur",
        unitCM: "cm",
        unitIN: "pouces",
        unitKG: "kg",
        unitLBS: "livres",
        formNotesLabel: "Notes",
        formNotesPlaceholder: "Entrez des notes pertinentes...",
        saveMeasurementButton: "Enregistrer Mesure",
        tableHeaderDate: "Date",
        tableHeaderMeasurementName: "Mesure",
        tableHeaderValue: "Valeur",
        measurementReminderLabel: "Rappel de Mesure",
        selectReminderFrequencyPlaceholder: "Sélectionnez la fréquence",
        reminderOff: "Désactivé",
        reminderDaily: "Quotidien",
        reminderWeekly: "Hebdomadaire",
        reminderBiWeekly: "Bihebdomadaire",
        reminderMonthly: "Mensuel",
        measurementSaved: "Mesure Enregistrée",
        measurementDeleted: "Mesure Supprimée",
        noMeasurementsYet: "Aucune mesure enregistrée pour l'instant. Ajoutez votre première !",
        formValidationAlert: "Veuillez remplir la date, le type de mesure et la valeur.",
    },
    workoutPlansPage: {
        title: "Programmes d'Entraînement",
        description: "Créez, gérez et partagez vos programmes d'entraînement.",
        createNewPlanButton: "Créer un Nouveau Programme",
        exercisesLabel: "Exercices",
        estDurationLabel: "Durée Estimée",
        startButton: "Commencer",
        dialogEditTitle: "Modifier le Programme d'Entraînement",
        dialogEditDescription: "Mettez à jour les détails de votre programme d'entraînement.",
        dialogCreateTitle: "Créer un Nouveau Programme d'Entraînement",
        dialogCreateDescription: "Concevez votre nouveau programme d'entraînement.",
        planNameLabel: "Nom du Programme",
        descriptionLabel: "Description",
        exerciseNameLabel: "Nom de l'Exercice",
        setsLabel: "Séries",
        repsLabel: "Répétitions",
        addThisExerciseButton: "Ajouter cet Exercice",
        addedExercisesLabel: "Exercices Ajoutés :",
        noExercisesAddedYet: "Aucun exercice ajouté à ce programme pour l'instant.",
        cancelButton: "Annuler",
        savePlanButton: "Enregistrer le Programme",
        toastPlanUpdatedTitle: "Programme Mis à Jour",
        toastPlanUpdatedDescription: '"{planName}" a été mis à jour.',
        toastPlanCreatedTitle: "Programme Créé",
        toastPlanCreatedDescription: '"{planName}" a été créé.',
        toastPlanDeletedTitle: "Programme Supprimé",
        toastPlanDeletedDescription: '"{planName}" a été supprimé.',
        toastLinkCopiedTitle: "Lien Copié !",
        toastLinkCopiedDescription: "Lien du programme d'entraînement copié dans le presse-papiers.",
        muscleSilhouetteAlt: "Groupes musculaires impliqués dans le programme",
        muscleGroupsLabel: "Groupes Musculaires",
    },
    startWorkoutPage: {
      title: "Commencer un Nouvel Entraînement",
      description: "Choisissez un programme pour commencer ou lancez une session ad-hoc.",
      selectPlanTitle: "Sélectionnez un Programme",
      noPlansAvailable: "Aucun programme d'entraînement disponible. Créez-en un d'abord !",
      startPlanButton: "Commencer Programme",
    },
    activeWorkoutPage: {
        title: "Entraînement Actif : {planName}",
        description: "Suivez vos séries, répétitions et poids pour cette session.",
        finishWorkoutButton: "Terminer l'Entraînement",
        logSetButton: "Enregistrer Série",
        planNotFound: "Programme d'entraînement non trouvé.",
        planNotFoundDescription: "Veuillez vérifier l'URL ou revenez en arrière pour sélectionner un programme valide.",
        loadingWorkout: "Chargement de l'Entraînement...",
        loadingDescription: "Veuillez patienter pendant que nous chargeons les détails du programme.",
        targetSetsLabel: "Séries Cibles",
        targetRepsLabel: "Répétitions Cibles",
        repsInputLabel: "Répétitions",
        weightInputLabel: "Poids (kg)",
        setColumnLabel: "Série",
        dateColumnLabel: "Date",
        repsColumnLabel: "Répétitions",
        weightColumnLabel: "Poids (kg)",
        toastSetLoggedTitle: "Série Enregistrée",
        toastSetLoggedDescription: "Série pour {exerciseName} enregistrée.",
        toastSetDeletedTitle: "Série Supprimée",
        toastWorkoutFinishedTitle: "Entraînement Terminé !",
        toastWorkoutFinishedDescription: "Excellent travail pour avoir terminé votre entraînement en {duration} !",
        overallProgressLabel: "Progression Globale de l'Entraînement",
        setCompletionLabel: "Séries : {completed}/{total}",
        noGifAvailable: "Aucun GIF disponible",
        exerciseDemoAlt: "démonstration de l'exercice",
        completeWorkoutButton: "Terminer l'Entraînement",
        workoutCompleteTitle: "Entraînement Terminé !",
        workoutCompleteDescription: "Vous avez terminé avec succès l'entraînement {planName}.",
        totalTimeLabel: "Temps Total",
        backToDashboardButton: "Retour à l'Accueil",
        confirmFinishTitle: "Terminer l'Entraînement ?",
        confirmFinishDescription: "Êtes-vous sûr de vouloir marquer cet entraînement comme terminé ?",
        confirmFinishButton: "Oui, Terminer",
        noSetsLoggedYet: "Aucune série enregistrée pour cet exercice.",
        sessionPBsLabel: "RP de Session",
        maxWeightLabel: "Poids Max",
        maxRepsLabel: "Rép. Max",
        repsUnitLabel: "réps",
        workoutInProgressTitle: "Entraînement en Cours",
        finishCurrentWorkoutPrompt: "Vous avez un entraînement actif. Veuillez le terminer ou l'abandonner avant d'en commencer un nouveau ou de créer/modifier des programmes.",
    },
    resumeWorkoutButton: {
      resumeTitle: "Reprendre l'entraînement",
      resume: "Reprendre : {planName}",
    }
  }
};


interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string | number | undefined>) => string;
  isClient: boolean;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(DEFAULT_LANGUAGE);
  const [isClient, setIsClient] = useState(false);

  useEffect(() => {
    setIsClient(true);
    let clientInitialLanguage = DEFAULT_LANGUAGE;
    try {
      const storedLanguage = localStorage.getItem(LANGUAGE_STORAGE_KEY) as Language | null;
      if (storedLanguage && translations[storedLanguage]) {
        clientInitialLanguage = storedLanguage;
      } else {
         localStorage.setItem(LANGUAGE_STORAGE_KEY, DEFAULT_LANGUAGE);
      }
    } catch (e) {
      console.warn('LanguageProvider: Failed to access localStorage. Using default language.', e);
    }

    if (clientInitialLanguage !== language) {
      setLanguageState(clientInitialLanguage);
    }
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const setLanguage = useCallback((newLanguage: Language) => {
    if (translations[newLanguage]) {
      try {
        localStorage.setItem(LANGUAGE_STORAGE_KEY, newLanguage);
      } catch (e) {
         console.warn('LanguageProvider: Failed to save language to localStorage.', e);
      }
      setLanguageState(newLanguage);
      if (typeof document !== 'undefined') {
        document.documentElement.lang = newLanguage;
      }
    } else {
      console.warn(`LanguageProvider: Attempted to set unsupported language "${newLanguage}"`);
    }
  }, []);

  const t = useCallback((key: string, replacements?: Record<string, string | number | undefined>): string => {
    const currentLang = isClient ? language : DEFAULT_LANGUAGE;
    const keys = key.split('.');
    let result: any = translations[currentLang];

    for (const k of keys) {
      result = result?.[k];
      if (result === undefined) {
        // Fallback to default language if key not found in current language
        let fallbackResult: any = translations[DEFAULT_LANGUAGE];
        for (const fk of keys) {
            fallbackResult = fallbackResult?.[fk];
            if (fallbackResult === undefined) {
              return replacements?.default?.toString() || key;
            }
        }
        result = fallbackResult;
        break;
      }
    }

    if (typeof result === 'string' && replacements) {
      const actualReplacements = { ...replacements };
      delete actualReplacements.default; // Don't replace the 'default' key itself

      return Object.entries(actualReplacements).reduce((acc, [placeholder, value]) => {
        const replacementValue = (typeof value === 'string' || typeof value === 'number') ? String(value) : '';
        return acc.replace(new RegExp(`{${placeholder}}`, 'g'), replacementValue);
      }, result);
    }
    
    // Return the default from replacements if provided and result is not a string, or the key itself
    return typeof result === 'string' ? result : (replacements?.default?.toString() || key) ;
  }, [language, isClient]);


  useEffect(() => {
    if (isClient) {
      document.documentElement.lang = language;
    }
  }, [language, isClient]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isClient }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

